import React, { createContext, useState, useContext } from 'react';

const translations = {
  EN: {
    // Header
    'nav.about': 'About us',
    'nav.platform': 'Platform',
    'nav.solution': 'Solution',
    'nav.usecase': 'Use case',
    'nav.sustainability': 'Sustainability',
    'nav.blog': 'Blog',
    'nav.resource': 'Careers',
    'nav.bookDemo': 'Book a demo',
    'nav.changeLang': 'Change Language',
    'nav.announcement.badge': 'New update:',
    'nav.announcement.text': 'Discover the new Udata AI ecosystem with superior performance',
    
    // Hero Section
    'hero.badge': 'AIoT PLATFORM FOR GREEN DIGITAL TRANSFORMATION',
    'hero.title.part1': 'Green digital transformation via',
    'hero.title.highlight': 'real-time operational intelligence',
    'hero.subtitle': 'Udata connects AI, IoT, and operational data into a centralized intelligence layer, giving businesses full visibility into production, logistics, finance, and energy flows — optimizing performance, controlling costs, and driving sustainability.',
    'hero.btn.freeTrial': 'Book a Demo',
    'hero.btn.seePlatform': 'Explore the Platform',
    'hero.cta.subtext': 'For manufacturing, logistics, industrial parks and enterprises needing real-time operational optimization',

    // TrustedBy
    'trusted.headline': 'Partnering with enterprises on the journey of operational optimization and sustainable development',
    'trusted.subtext': 'Udata is built for organizations with complex operational systems, where data, performance, costs, and sustainability must be managed through a unified platform.',
    'trusted.title': 'Trusted by Vietnam\'s Leading Enterprises',
    'trusted.stat1.label': 'Enterprises Deployed',
    'trusted.stat2.label': 'Data Points / Day',
    'trusted.stat3.label': 'Average Energy Savings',
    'trusted.stat4.label': 'Platform Uptime SLA',

    // CoreInsight
    'core.badge': 'ENTERPRISE CHALLENGES',
    'core.title.part1': 'Businesses do not lack data. They lack a ',
    'core.title.highlight': 'unified operational intelligence layer.',
    'core.subtitle': 'In many enterprises, data is fragmented across ERP, production, logistics, finance, energy, and internal operational tools. Without a unified connectivity and analytics layer, leadership struggles to see the real-time picture, detect bottlenecks, and accurately measure the effectiveness of digital transformation.',
    'core.feature1.title': 'Data Fragmentation',
    'core.feature1.desc': 'Operational information is divided across multiple systems, departments, and processes, making it hard to gain a unified perspective.',
    'core.feature2.title': 'Lack of Real-time Observation',
    'core.feature2.desc': 'Leaders struggle to simultaneously monitor production, logistics, energy, costs, and performance as issues arise.',
    'core.feature3.title': 'Delayed Decision Making',
    'core.feature3.desc': 'Manual reporting and delayed data lead to missed optimization opportunities, while costs and bottlenecks accumulate.',
    'core.feature4.title': 'ESG & Efficiency Pressure',
    'core.feature4.desc': 'Enterprises need transparent, measurable data to optimize operations, manage emissions, and meet sustainable development standards.',

    // BentoGrid / Ecosystem
    'bento.badge': 'UDATA ECOSYSTEM',
    'bento.title': 'AIoT Ecosystem for Smart Operations',
    'bento.subtitle': 'Every enterprise has a different operational system. Udata is flexibly designed to connect, analyze, and optimize data for specific practical scenarios — from factory monitoring, operational data consolidation to carbon management and internal knowledge automation.',

    'bento.uboard.label': 'Factory Intelligence',
    'bento.uboard.name': 'Uboard',
    'bento.uboard.title': 'AI + IoT monitoring and factory operation optimization',
    'bento.uboard.desc': 'Monitor equipment data, energy, and performance in real-time to detect anomalies and optimize factory operations.',
    'bento.uboard.cta': 'Explore Uboard',
    'bento.uboard.visualText': 'Realtime monitoring. Operation optimization. Performance enhancement.',

    'bento.ugate.label': 'Central AI Layer',
    'bento.ugate.name': 'Ugate',
    'bento.ugate.title': 'Central AI layer connecting and analyzing enterprise operational data',
    'bento.ugate.desc': 'Consolidate all data sources into a central intelligence layer, empowering leaders with full visibility and instant decision-making.',
    'bento.ugate.cta': 'Learn about Ugate',
    'bento.ugate.visualText': 'From Data Flow to Business Flow',

    'bento.uzero.label': 'Carbon & ESG Management',
    'bento.uzero.name': 'Uzero',
    'bento.uzero.title': 'Carbon and emissions management solution',
    'bento.uzero.desc': 'Emissions measurement and management system, creating a transparent foundation for ESG standards and green growth.',
    'bento.uzero.cta': 'Learn about Uzero',
    'bento.uzero.visualText': 'Carbon Data. ESG Readiness. Sustainable Growth.',

    'bento.mini.label': 'AI Knowledge Assistant',
    'bento.mini.name': 'MiniUgate',
    'bento.mini.title': 'AI chatbot for customer care and internal knowledge processing',
    'bento.mini.desc': 'Automate responses and leverage internal knowledge with AI, accelerating information processing and enhancing customer experience.',
    'bento.mini.cta': 'View MiniUgate',
    'bento.mini.visualText': 'AI Assistant for enterprise knowledge',

    // Workflow
    'workflow.badge': 'DEPLOYMENT WORKFLOW',
    'workflow.title': 'From fragmented data to a smart operational system',
    'workflow.subtitle': 'Udata accompanies businesses from problem surveys, data architecture design, AIoT integration to operation, optimization, and system-wide expansion.',
    'workflow.step1.title': 'Survey & Problem Identification',
    'workflow.step1.desc': 'Analyze operational models, existing systems, required data sources, and enterprise efficiency goals.',
    'workflow.step2.title': 'Data Architecture & AIoT Design',
    'workflow.step2.desc': 'Build data flows, integration points, dashboards, alerts, and metrics suitable for each operational model.',
    'workflow.step3.title': 'Integration & Pilot Deployment',
    'workflow.step3.desc': 'Connect actual devices, systems, and data; verify effectiveness per use case before scaling.',
    'workflow.step4.title': 'Operation, Optimization & Expansion',
    'workflow.step4.desc': 'Monitor results, fine-tune analytical models, and expand solutions to new areas, factories, or processes.',
    'workflow.cta.title': 'Want to know which Udata solution fits your business?',
    'workflow.cta.desc': 'The Udata team will work with you to identify use cases, required data connections, and a suitable deployment roadmap.',
    'workflow.cta.btn': 'Talk to an expert',

    // CaseStudies
    'case.badge': 'SUCCESS STORIES',
    'case.title': 'See how Udata helps enterprises transform',
    'case.c1.cat': 'Manufacturing',
    'case.c1.title': 'Realtime Factory Operation Optimization',
    'case.c1.desc': 'Connect equipment, production lines, and energy data to help factories monitor performance, detect bottlenecks, and improve operational capabilities.',
    'case.c2.cat': 'Energy Optimization',
    'case.c2.title': 'Energy & Operational Cost Control',
    'case.c2.desc': 'Real-time energy consumption tracking, detect waste areas, and support enterprises in optimizing costs based on measured data.',
    'case.c3.cat': 'ESG & Carbon',
    'case.c3.title': 'Building Data Foundation for Sustainability',
    'case.c3.desc': 'Standardize emission data and operational metrics, making enterprises ready for ESG, carbon reporting, and international audit systems.',
    'case.c4.cat': 'Enterprise Operations',
    'case.c4.title': 'Consolidating Fragmented Data into an AI Layer',
    'case.c4.desc': 'Connect data from ERP, logistics, manufacturing, and finance to create a unified view for leadership and support faster decision making.',
    'case.cta': 'View use case',

    // Compliance
    'compliance.badge': 'RELIABILITY & SUSTAINABILITY',
    'compliance.title.line1': 'Enterprise standards for',
    'compliance.title.highlight1': 'secure data',
    'compliance.title.mid': ' and ',
    'compliance.title.highlight2': 'sustainable operations',
    'compliance.subtitle': 'Udata is built with an enterprise mindset: securing operational data, standardizing energy information, supporting ESG/carbon transparency, and meeting international audit requirements in the green digital transformation journey.',
    'compliance.item1.title': 'ISO 27001',
    'compliance.item1.desc': 'Information Security Management',
    'compliance.item2.title': 'ISO 50001',
    'compliance.item2.desc': 'Energy Management',
    'compliance.item3.title': 'GHG Protocol',
    'compliance.item3.desc': 'Emissions Inventory',
    'compliance.item4.title': 'Sao Khue 2025',
    'compliance.item4.desc': 'VINASA Best AIoT',
    'compliance.item5.title': 'COP28',
    'compliance.item5.desc': 'Global Climate Orientation',
    'compliance.item6.title': 'TCFD',
    'compliance.item6.desc': 'Climate Risk Transparency',

    // ExperienceCTA
    'cta.title.part1': 'Ready to turn operational data into a ',
    'cta.title.highlight': 'growth advantage?',
    'cta.subtitle': 'Join Udata in building a central operational intelligence layer for your enterprise — where real-time data becomes the foundation for accurate decisions, higher efficiency, and sustainable development.',
    'cta.input.placeholder': 'Enter your business email',
    'cta.btn.demo': 'Book a Demo',
    'cta.note': 'The Udata team will contact you to advise on a roadmap suited for your operational model.',

    // Careers Page
    'careers.hero.badge': 'WE ARE HIRING',
    'careers.hero.title.part1': 'Join the team building the future of ',
    'careers.hero.title.highlight': 'AI & IoT',
    'careers.hero.subtitle': 'UDATA is looking for young, proactive individuals ready to grow in a practical technology environment.',
    'careers.hero.btn': 'View open roles',

    'careers.why.title': 'Why choose Udata?',
    'careers.why.subtitle': 'We don\'t just build software, we shape how businesses interact with data.',
    'careers.why.1.title': 'Practical Tech Environment',
    'careers.why.1.desc': 'Directly participate in AI, AIoT, Smart Factory, and Digital Transformation projects for manufacturing enterprises.',
    'careers.why.2.title': 'Accelerate Career in AI Era',
    'careers.why.2.desc': 'Work with a high-speed tech team, develop solution mindset and practical B2B skills.',
    'careers.why.3.title': 'Create Real Business Value',
    'careers.why.3.desc': 'Your solutions help businesses optimize operations, improve data utilization, and develop sustainably.',

    'careers.jobs.title': 'Open Positions',
    'careers.jobs.subtitle': 'Find a role that matches your strengths and start your journey at Udata today.',
    'careers.jobs.filter.all': 'All',
    'careers.jobs.filter.sales': 'Sales',
    'careers.jobs.filter.engineering': 'Engineering',
    'careers.jobs.filter.office': 'Office',
    'careers.jobs.filter.marketing': 'Marketing',
    'careers.jobs.btn.view': 'View details',
    'careers.jobs.btn.apply': 'Apply now',

    'careers.process.title': 'Hiring Process',
    'careers.process.subtitle': 'Fair, transparent, and fast is our commitment in the hiring process.',
    'careers.process.1.title': 'Apply',
    'careers.process.1.desc': 'Send your best CV and portfolio to the Talent Acquisition team.',
    'careers.process.2.title': 'Interview',
    'careers.process.2.desc': 'Direct discussion about technical skills and cultural fit with the leadership team.',
    'careers.process.3.title': 'Offer',
    'careers.process.3.desc': 'Welcome to the Udata family to conquer new heights together.',

    'careers.cta.title': 'Can\'t find a suitable position?',
    'careers.cta.subtitle': 'Don\'t hesitate to send us your CV. We are always ready to welcome talents who are eager to contribute.',
    'careers.cta.btn': 'Send Open Application',

    // About Us Page
    'about.badge': 'About Udata',
    'about.hero.subtitle': 'Building an operational intelligence layer for <br /><span class="bg-gradient-to-r from-[#22D3EE] to-[#10F0CB] bg-clip-text text-transparent">green digital transformation</span>',
    'about.intro.title': 'From operational data to sustainable growth',
    'about.intro.p1': 'Udata was created to help enterprises enter the era of green digital transformation through an intelligent AIoT system. We help businesses digitize operational data, control real-time data flows, and optimize performance in line with each organization\'s development strategy.',
    'about.intro.p2': 'Instead of just providing monitoring software, Udata acts as a central operational intelligence layer. The platform connects fragmented operational systems and tools into a unified flow of information that can be analyzed, measured, and transformed into specific actions.',
    'about.intro.p3': 'Through the ecosystem of Ugate, Uboard, Uzero, and MiniUgate, Udata supports businesses to turn operational data into valuable insights, control costs, improve performance, accelerate internal knowledge processing, and build a data foundation for long-term ESG, carbon, and sustainable development.',
    'about.intro.quote': 'Sustainable development is not just a goal. It is a mission Udata shares with every customer.',
    'about.vision.title': 'Vision',
    'about.vision.desc': 'To become the leading green digital transformation platform for businesses in Vietnam and internationally, helping businesses operate intelligently, optimally, and sustainably through AIoT, real-time data, and a centralized operational intelligence layer.',
    'about.mission.title': 'Mission',
    'about.mission.desc': 'Help businesses digitize and control operational data in real-time, optimize performance, accelerate internal knowledge processing, and build a long-term sustainable development foundation.',
    'about.position.title': 'Position',
    'about.position.desc': 'Udata is the central operational intelligence layer that helps businesses connect data, detect bottlenecks, optimize cash flow, improve performance, and drive green digital transformation with measurable results.',
    'about.core.title': 'Core Values',
    'about.core.subtitle': 'Smart technology needs to create real impact',
    'about.core.desc': 'Udata develops technology with an enterprise mindset, focusing on data, real efficiency, and the ability to accompany businesses long-term.',
    'about.core.intelligent.desc': 'Data-driven, AIoT, and operational insights to help businesses make more accurate decisions.',
    'about.core.reliable.desc': 'Build a stable, secure, and reliable platform for long-term enterprise scenarios.',
    'about.core.sustainable.desc': 'Optimize operational performance coupled with energy saving, ESG, carbon, and sustainable development.',
    
    // Footer
    'footer.quick_links': 'Quick Links',
    'footer.products': 'Products',
    'footer.applications': 'Applications',
    'footer.app1': 'Rooftop Solar',
    'footer.app2': 'Elevators',
    'footer.app3': 'Enterprise AI Assistant',
    'footer.app4': 'Q&A AI Assistant',
    'footer.contact': 'Contact Information',
    'footer.hn_office': 'Hanoi Office:',
    'footer.hn_address': '9th Floor, Millennium Building,<br/>4 Quang Trung, Ha Dong District, Hanoi.',
    'footer.hcm_office': 'Ho Chi Minh Office:',
    'footer.hcm_address': '6th Floor, DHG Building, 31-33<br/>Street 18, Thong Tay Hoi Ward,<br/>Ho Chi Minh City.',
    'footer.profile': 'Company Profile',
    'footer.download_profile': 'Download Company Profile (PDF)',

    'about.awards.title': 'Awards & Recognition',
    'about.awards.subtitle': "A milestone recognizing Udata's AIoT capabilities",
    'about.awards.p1': 'In 2025, Udata\'s Uboard was honored at the Sao Khue Awards 2025 in the category of New products, solutions, software, and services. This is a milestone recognizing Udata\'s efforts in developing an AIoT platform that helps businesses collect, monitor, analyze, and optimize operational data.',
    'about.awards.p2': 'This recognition provides further motivation for Udata to continue expanding its ecosystem of solutions, from factory monitoring and operational data consolidation to carbon management and sustainable development.',
    'about.awards.p3': '',
    'about.cta.title': 'Speak with data. Partner for results.',
    'about.cta.subtitle': 'Build a smart operational platform for your business with Udata',
    'about.cta.btn1': 'Leave your phone number',
    'about.cta.btn2': 'Book a consultation',

    // Free Trial Page
    'trial.title': 'Experience the Udata platform with a 30-minute live demo.',
    'trial.subtitle': 'Always on. Always accurate. <br /> Udata - Accompanying businesses in the era of technology and sustainability.',
    'trial.list_title': 'In the 30-minute demo, we will explore with you:',
    'trial.item1.title': 'Cost and performance optimization',
    'trial.item1.desc': 'See firsthand how the Udata system helps save energy, reduce operating costs, and improve equipment performance.',
    'trial.item2.title': 'Interactive demo experience',
    'trial.item2.desc': 'Try out actual dashboards - monitor energy data, alerts, and automated reports.',
    'trial.item3.title': '1:1 expert consultation',
    'trial.item3.desc': 'Discuss your specific business needs and receive tailored solution recommendations.',
    'trial.item4.title': 'Guides & 30-day free trial',
    'trial.item4.desc': 'Receive detailed implementation guides and 30 days of full access to the Udata platform for free.',
    'trial.form.title': 'Register for a consultation and 30-day free trial',
    'trial.form.name': 'Full Name',
    'trial.form.name_placeholder': 'Enter your full name',
    'trial.form.company': 'Company Name',
    'trial.form.company_placeholder': 'Enter your company name',
    'trial.form.phone': 'Phone Number',
    'trial.form.phone_placeholder': 'Enter your phone number',
    'trial.form.email': 'Email Address',
    'trial.form.email_placeholder': 'Enter your email',
    'trial.form.industry': 'Industry',
    'trial.form.industry_placeholder': 'Select industry',
    'trial.form.request': 'Request details',
    'trial.form.request_placeholder': 'Please describe what you are looking for...',
    'trial.form.subscribe': 'Yes, I want to receive the latest news about Udata services and promotions via email or phone.',
    'trial.form.submit': 'Submit',
    'trial.form.success': 'Registration successful! We will contact you shortly.',
    'trial.form.error': 'An error occurred. Please try again.',

    // Stub Pages
    'solutions.badge': 'Enterprise Solutions',
    'solutions.title': 'Comprehensive Solutions for <br/><span class="text-electric-cyan">digital transformation</span>',
    'solutions.desc': 'From hardware monitoring to AI operation, Udata provides a complete ecosystem to help businesses optimize resources and breakthrough revenue.',
    'solutions.coming_soon': 'Solution details page is being designed...',

    'usecases.badge': 'Practice & Applications',
    'usecases.title': 'How customers <br/>apply <span class="text-electric-cyan">Udata</span>',
    'usecases.desc': 'Explore real-world case studies from multiple sectors: Industrial Manufacturing, Healthcare, Retail, and Customer Service.',
    'usecases.coming_soon': 'Use Cases page is gathering data...',

    'sustainability.badge': 'Vision 2050',
    'sustainability.title': '<span class="text-sustain-teal">Sustainable</span> Development <br/>with Green AI',
    'sustainability.desc': 'Udata is committed to accompanying businesses in measuring emissions, optimizing energy, and aiming for the global Net Zero goal.',
    'sustainability.coming_soon': 'Sustainability Report is being prepared...',

    'blog.badge': 'News & Articles',
    'blog.title': 'Discover knowledge with <br/><span class="text-electric-cyan">Udata Blog</span>',
    'blog.desc': 'Catch up on the latest technology trends in AI, IoT, digital transformation, and sustainable development from our experts.',
    'blog.coming_soon': 'Blog page is being updated with content...',
  },
  VI: {
    // Header
    'nav.about': 'Về chúng tôi',
    'nav.platform': 'Nền tảng',
    'nav.solution': 'Giải pháp',
    'nav.usecase': 'Tình huống sử dụng',
    'nav.sustainability': 'Phát triển bền vững',
    'nav.blog': 'Bài viết',
    'nav.resource': 'Tuyển dụng',
    'nav.bookDemo': 'Đặt lịch Demo',
    'nav.changeLang': 'Đổi ngôn ngữ',
    'nav.announcement.badge': 'Mới cập nhật:',
    'nav.announcement.text': 'Khám phá hệ sinh thái AIoT cho vận hành thông minh và chuyển đổi số xanh',
    
    // Hero Section
    'hero.badge': 'NỀN TẢNG AIoT CHO CHUYỂN ĐỔI SỐ XANH',
    'hero.title.part1': 'Chuyển đổi số xanh bằng',
    'hero.title.highlight': 'trí tuệ vận hành thời gian thực',
    'hero.subtitle': 'Udata kết nối AI, IoT và dữ liệu vận hành vào một lớp trí tuệ tập trung, giúp doanh nghiệp nhìn thấy toàn bộ dòng chảy<br className="hidden md:block"/>sản xuất, kho vận, tài chính và năng lượng — từ đó tối ưu hiệu suất, kiểm soát chi phí và phát triển bền vững.',
    'hero.btn.freeTrial': 'Đặt lịch Demo',
    'hero.btn.seePlatform': 'Khám phá nền tảng',
    'hero.cta.subtext': 'Dành cho doanh nghiệp sản xuất, logistics, khu công nghiệp và enterprise cần tối ưu vận hành bằng dữ liệu realtime',

    // TrustedBy
    'trusted.headline': 'Đồng hành cùng doanh nghiệp trong hành trình tối ưu vận hành và phát triển bền vững',
    'trusted.subtext': 'Udata được xây dựng cho các tổ chức có hệ thống vận hành phức tạp, nơi dữ liệu, hiệu suất, chi phí và tính bền vững cần được quản trị bằng một nền tảng thống nhất.',
    'trusted.title': 'Đồng hành cùng doanh nghiệp trong hành trình tối ưu vận hành và phát triển bền vững',
    'trusted.stat1.label': 'Doanh nghiệp đã triển khai',
    'trusted.stat2.label': 'Điểm dữ liệu / Ngày',
    'trusted.stat3.label': 'Tiết kiệm năng lượng trung bình',
    'trusted.stat4.label': 'SLA hoạt động của nền tảng',

    // CoreInsight
    'core.badge': 'BÀI TOÁN DOANH NGHIỆP',
    'core.title.part1': 'Dữ liệu không thiếu. Doanh nghiệp thiếu một ',
    'core.title.highlight': 'lớp trí tuệ vận hành tập trung.',
    'core.subtitle': 'Trong nhiều doanh nghiệp, dữ liệu đang nằm rời rạc giữa ERP, sản xuất, kho vận, tài chính, năng lượng và các công cụ vận hành nội bộ. Khi thiếu một lớp kết nối và phân tích thống nhất, ban lãnh đạo khó nhìn thấy bức tranh realtime, khó phát hiện điểm nghẽn và khó đo lường chính xác hiệu quả chuyển đổi số.',
    'core.feature1.title': 'Dữ liệu phân mảnh',
    'core.feature1.desc': 'Thông tin vận hành bị chia cắt giữa nhiều hệ thống, phòng ban và quy trình, khiến doanh nghiệp khó có một góc nhìn thống nhất.',
    'core.feature2.title': 'Thiếu quan sát realtime',
    'core.feature2.desc': 'Lãnh đạo khó theo dõi đồng thời sản xuất, kho vận, năng lượng, chi phí và hiệu suất ngay khi vấn đề phát sinh.',
    'core.feature3.title': 'Quyết định đến chậm',
    'core.feature3.desc': 'Báo cáo thủ công và dữ liệu trễ khiến cơ hội tối ưu bị bỏ lỡ, trong khi chi phí và điểm nghẽn tiếp tục tích lũy.',
    'core.feature4.title': 'Áp lực ESG & hiệu quả',
    'core.feature4.desc': 'Doanh nghiệp cần dữ liệu minh bạch, đo lường được để tối ưu vận hành, quản trị phát thải và đáp ứng các tiêu chuẩn phát triển bền vững.',

    // BentoGrid / Ecosystem
    'bento.badge': 'HỆ SINH THÁI UDATA',
    'bento.title': 'Hệ sinh thái AIoT cho vận hành thông minh',
    'bento.subtitle': 'Mỗi doanh nghiệp có một hệ thống vận hành khác nhau. Udata được thiết kế linh hoạt để kết nối, phân tích và tối ưu dữ liệu theo từng bài toán thực tế — từ giám sát nhà máy, hợp nhất dữ liệu vận hành đến quản trị carbon và tự động hóa tri thức nội bộ.',

    'bento.uboard.label': 'Trí tuệ Nhà máy',
    'bento.uboard.name': 'Uboard',
    'bento.uboard.title': 'AI + IoT giám sát và tối ưu vận hành nhà máy',
    'bento.uboard.desc': 'Theo dõi dữ liệu thiết bị, năng lượng và hiệu suất theo thời gian thực để phát hiện bất thường và tối ưu vận hành nhà máy.',
    'bento.uboard.cta': 'Khám phá Uboard',
    'bento.uboard.visualText': 'Giám sát realtime. Tối ưu vận hành. Nâng cao hiệu suất.',

    'bento.ugate.label': 'Lớp AI Trung tâm',
    'bento.ugate.name': 'Ugate',
    'bento.ugate.title': 'Lớp AI trung tâm kết nối và phân tích dữ liệu vận hành doanh nghiệp',
    'bento.ugate.desc': 'Hợp nhất mọi nguồn dữ liệu (ERP, sản xuất, tài chính...) vào một lớp trí tuệ trung tâm, giúp lãnh đạo nhìn thấu toàn cảnh và ra quyết định tức thời.',
    'bento.ugate.cta': 'Tìm hiểu Ugate',
    'bento.ugate.visualText': 'From Data Flow to Business Flow',

    'bento.uzero.label': 'Quản trị Carbon & ESG',
    'bento.uzero.name': 'Uzero',
    'bento.uzero.title': 'Giải pháp quản trị carbon và phát thải',
    'bento.uzero.desc': 'Hệ thống đo lường và quản trị dữ liệu phát thải, tạo nền tảng minh bạch đáp ứng tiêu chuẩn ESG và lộ trình tăng trưởng xanh.',
    'bento.uzero.cta': 'Tìm hiểu Uzero',
    'bento.uzero.visualText': 'Carbon Data. ESG Readiness. Sustainable Growth.',

    'bento.mini.label': 'Trợ lý Tri thức AI',
    'bento.mini.name': 'MiniUgate',
    'bento.mini.title': 'AI chatbot cho chăm sóc khách hàng và xử lý tri thức nội bộ',
    'bento.mini.desc': 'Tự động hóa phản hồi và khai thác tri thức nội bộ bằng AI, giúp tăng tốc xử lý thông tin và nâng cao trải nghiệm khách hàng.',
    'bento.mini.cta': 'Xem MiniUgate',
    'bento.mini.visualText': 'Trợ lý AI cho tri thức doanh nghiệp',

    // Workflow
    'workflow.badge': 'QUY TRÌNH TRIỂN KHAI',
    'workflow.title': 'Từ dữ liệu phân mảnh đến hệ thống vận hành thông minh',
    'workflow.subtitle': 'Udata đồng hành cùng doanh nghiệp từ khảo sát bài toán, thiết kế kiến trúc dữ liệu, tích hợp AIoT đến vận hành, tối ưu và mở rộng trên toàn hệ thống.',
    'workflow.step1.title': 'Khảo sát & xác định bài toán',
    'workflow.step1.desc': 'Phân tích mô hình vận hành, hệ thống hiện có, nguồn dữ liệu cần kết nối và mục tiêu hiệu quả của doanh nghiệp.',
    'workflow.step2.title': 'Thiết kế kiến trúc dữ liệu & AIoT',
    'workflow.step2.desc': 'Xây dựng luồng dữ liệu, điểm tích hợp, dashboard, cảnh báo và bộ chỉ số đo lường phù hợp với từng mô hình vận hành.',
    'workflow.step3.title': 'Tích hợp & triển khai thử nghiệm',
    'workflow.step3.desc': 'Kết nối thiết bị, hệ thống và dữ liệu thực tế; kiểm chứng hiệu quả theo từng use case trước khi mở rộng.',
    'workflow.step4.title': 'Vận hành, tối ưu & mở rộng',
    'workflow.step4.desc': 'Theo dõi kết quả, tinh chỉnh mô hình phân tích và mở rộng giải pháp sang các khu vực, nhà máy hoặc quy trình mới.',
    'workflow.cta.title': 'Bạn muốn biết Udata phù hợp với bài toán nào của doanh nghiệp?',
    'workflow.cta.desc': 'Đội ngũ Udata sẽ cùng bạn xác định use case, dữ liệu cần kết nối và lộ trình triển khai phù hợp.',
    'workflow.cta.btn': 'Trao đổi với chuyên gia',

    // CaseStudies
    'case.badge': 'CÂU CHUYỆN THÀNH CÔNG',
    'case.title': 'Xem cách Udata giúp các doanh nghiệp chuyển đổi',
    'case.c1.cat': 'Manufacturing',
    'case.c1.title': 'Tối ưu vận hành nhà máy bằng dữ liệu realtime',
    'case.c1.desc': 'Kết nối dữ liệu thiết bị, dây chuyền và năng lượng để giúp nhà máy theo dõi hiệu suất, phát hiện điểm nghẽn và nâng cao năng lực vận hành.',
    'case.c2.cat': 'Energy Optimization',
    'case.c2.title': 'Kiểm soát năng lượng và chi phí vận hành',
    'case.c2.desc': 'Theo dõi tiêu thụ năng lượng theo thời gian thực, phát hiện khu vực lãng phí và hỗ trợ doanh nghiệp tối ưu chi phí dựa trên dữ liệu đo lường được.',
    'case.c3.cat': 'ESG & Carbon',
    'case.c3.title': 'Xây dựng nền tảng dữ liệu cho phát triển bền vững',
    'case.c3.desc': 'Chuẩn hóa dữ liệu phát thải và chỉ số vận hành, giúp doanh nghiệp sẵn sàng hơn cho ESG, carbon reporting và các hệ thống audit quốc tế.',
    'case.c4.cat': 'Enterprise Operations',
    'case.c4.title': 'Hợp nhất dữ liệu phân mảnh thành một lớp trí tuệ vận hành',
    'case.c4.desc': 'Kết nối dữ liệu từ ERP, kho vận, sản xuất và tài chính để tạo góc nhìn thống nhất cho ban lãnh đạo và hỗ trợ ra quyết định nhanh hơn.',
    'case.cta': 'Xem tình huống ứng dụng',

    // Compliance
    'compliance.badge': 'TIN CẬY & PHÁT TRIỂN BỀN VỮNG',
    'compliance.title.line1': 'Chuẩn mực enterprise cho',
    'compliance.title.highlight1': 'dữ liệu an toàn',
    'compliance.title.mid': ' và ',
    'compliance.title.highlight2': 'vận hành bền vững',
    'compliance.subtitle': 'Udata được xây dựng theo tư duy enterprise: bảo mật dữ liệu vận hành, chuẩn hóa thông tin năng lượng, hỗ trợ minh bạch ESG/carbon và đáp ứng các yêu cầu audit quốc tế trong hành trình chuyển đổi số xanh.',
    'compliance.item1.title': 'ISO 27001',
    'compliance.item1.desc': 'Quản trị an toàn thông tin',
    'compliance.item2.title': 'ISO 50001',
    'compliance.item2.desc': 'Quản trị năng lượng',
    'compliance.item3.title': 'GHG Protocol',
    'compliance.item3.desc': 'Kiểm kê Khí thải',
    'compliance.item4.title': 'Sao Khuê 2025',
    'compliance.item4.desc': 'AIoT xuất sắc nhất từ VINASA',
    'compliance.item5.title': 'COP28',
    'compliance.item5.desc': 'Định hướng khí hậu toàn cầu',
    'compliance.item6.title': 'TCFD',
    'compliance.item6.desc': 'Minh bạch rủi ro khí hậu',

    // ExperienceCTA
    'cta.title.part1': 'Sẵn sàng biến dữ liệu vận hành thành ',
    'cta.title.highlight': 'lợi thế tăng trưởng?',
    'cta.subtitle': 'Hãy cùng Udata xây dựng lớp trí tuệ vận hành trung tâm cho doanh nghiệp của bạn — nơi dữ liệu realtime trở thành nền tảng cho quyết định chính xác, hiệu suất cao hơn và phát triển bền vững hơn.',
    'cta.input.placeholder': 'Nhập email doanh nghiệp của bạn',
    'cta.btn.demo': 'Đặt lịch Demo',
    'cta.note': 'Đội ngũ Udata sẽ liên hệ để tư vấn lộ trình phù hợp với mô hình vận hành của doanh nghiệp.',

    // Careers Page
    'careers.hero.badge': 'ĐANG TUYỂN DỤNG',
    'careers.hero.title.part1': 'Gia nhập đội ngũ kiến tạo tương lai ',
    'careers.hero.title.highlight': 'AI & IoT',
    'careers.hero.subtitle': 'UDATA đang tìm kiếm những nhân sự trẻ, chủ động và sẵn sàng phát triển trong môi trường công nghệ thực chiến.',
    'careers.hero.btn': 'Xem các vị trí trống',

    'careers.why.title': 'Tại sao chọn Udata?',
    'careers.why.subtitle': 'Chúng tôi không chỉ xây dựng phần mềm, chúng tôi định hình cách doanh nghiệp tương tác với dữ liệu.',
    'careers.why.1.title': 'Môi trường Công nghệ Thực chiến',
    'careers.why.1.desc': 'Tham gia trực tiếp vào các dự án AI, AIoT, Smart Factory và Chuyển đổi số cho doanh nghiệp sản xuất.',
    'careers.why.2.title': 'Tăng tốc Sự nghiệp trong Kỷ nguyên AI',
    'careers.why.2.desc': 'Làm việc cùng đội ngũ công nghệ tốc độ cao, phát triển tư duy solution và kỹ năng thực chiến B2B.',
    'careers.why.3.title': 'Tạo ra Giá trị cho Doanh nghiệp Thực',
    'careers.why.3.desc': 'Các giải pháp của bạn giúp doanh nghiệp tối ưu vận hành, nâng cao hiệu suất sử dụng dữ liệu và phát triển bền vững.',

    'careers.jobs.title': 'Vị trí đang tuyển',
    'careers.jobs.subtitle': 'Tìm thấy vị trí phù hợp với thế mạnh của bạn và bắt đầu hành trình tại Udata ngay hôm nay.',
    'careers.jobs.filter.all': 'Tất cả',
    'careers.jobs.filter.sales': 'Kinh doanh',
    'careers.jobs.filter.engineering': 'Engineering',
    'careers.jobs.filter.office': 'Văn phòng',
    'careers.jobs.filter.marketing': 'Marketing',
    'careers.jobs.btn.view': 'Xem chi tiết',
    'careers.jobs.btn.apply': 'Ứng tuyển ngay',

    'careers.process.title': 'Quy trình tuyển dụng',
    'careers.process.subtitle': 'Công bằng, minh bạch và nhanh chóng là cam kết của chúng tôi trong quy trình tuyển dụng.',
    'careers.process.1.title': 'Ứng tuyển',
    'careers.process.1.desc': 'Gửi CV và portfolio ấn tượng nhất của bạn cho đội ngũ Talent Acquisition.',
    'careers.process.2.title': 'Phỏng vấn',
    'careers.process.2.desc': 'Trao đổi trực tiếp về kỹ năng chuyên môn và sự phù hợp về văn hóa với đội ngũ lãnh đạo.',
    'careers.process.3.title': 'Nhận Offer',
    'careers.process.3.desc': 'Chào mừng bạn gia nhập đại gia đình Udata để cùng nhau chinh phục những đỉnh cao mới.',

    'careers.cta.title': 'Chưa thấy vị trí phù hợp?',
    'careers.cta.subtitle': 'Đừng ngần ngại gửi CV của bạn cho chúng tôi. Chúng tôi luôn sẵn lòng chào đón những nhân tài khao khát cống hiến.',
    'careers.cta.btn': 'Gửi CV Tự do',

    // About Us Page
    'about.badge': 'Về Udata',
    'about.hero.subtitle': 'Kiến tạo lớp trí tuệ vận hành cho <span class="bg-gradient-to-r from-[#22D3EE] to-[#10F0CB] bg-clip-text text-transparent">chuyển đổi số xanh</span>',
    'about.intro.title': 'Từ dữ liệu vận hành đến tăng trưởng bền vững',
    'about.intro.p1': 'Udata được tạo ra nhằm giúp doanh nghiệp bước vào kỷ nguyên chuyển đổi số xanh thông qua hệ thống AIoT thông minh. Chúng tôi giúp doanh nghiệp số hóa dữ liệu vận hành, kiểm soát dòng dữ liệu theo thời gian thực và tối ưu hiệu suất phù hợp với chiến lược phát triển của từng tổ chức.',
    'about.intro.p2': 'Thay vì chỉ cung cấp một phần mềm giám sát, Udata đóng vai trò như một lớp trí tuệ vận hành trung tâm. Nền tảng giúp kết nối các hệ thống và công cụ vận hành đang phân mảnh thành một dòng thông tin thống nhất, có thể phân tích, đo lường và chuyển hóa thành hành động cụ thể.',
    'about.intro.p3': 'Thông qua hệ sinh thái Ugate, Uboard, Uzero và MiniUgate, Udata hỗ trợ doanh nghiệp biến dữ liệu vận hành thành insight có giá trị, kiểm soát chi phí, nâng cao hiệu suất, tăng tốc xử lý tri thức nội bộ và xây dựng nền tảng dữ liệu phục vụ ESG, carbon và phát triển bền vững trong dài hạn.',
    'about.intro.quote': 'Phát triển bền vững không chỉ là mục tiêu. Đó là sứ mệnh Udata chia sẻ cùng từng khách hàng.',
    'about.vision.title': 'Tầm nhìn',
    'about.vision.desc': 'Trở thành nền tảng chuyển đổi số xanh hàng đầu cho doanh nghiệp tại Việt Nam và quốc tế, giúp doanh nghiệp vận hành thông minh, tối ưu và bền vững thông qua AIoT, dữ liệu realtime và lớp trí tuệ vận hành tập trung.',
    'about.mission.title': 'Sứ mệnh',
    'about.mission.desc': 'Giúp doanh nghiệp số hóa và kiểm soát dữ liệu vận hành theo thời gian thực, tối ưu hiệu suất, tăng tốc xử lý tri thức nội bộ và xây dựng nền tảng phát triển bền vững dài hạn.',
    'about.position.title': 'Định vị',
    'about.position.desc': 'Udata là lớp trí tuệ vận hành trung tâm giúp doanh nghiệp kết nối dữ liệu, phát hiện điểm nghẽn, tối ưu dòng tiền, nâng cao hiệu suất và thúc đẩy chuyển đổi số xanh bằng những kết quả có thể đo lường.',
    'about.core.title': 'Giá trị cốt lõi',
    'about.core.subtitle': 'Công nghệ thông minh cần tạo ra tác động thực tế',
    'about.core.desc': 'Udata phát triển công nghệ với tư duy enterprise, tập trung vào dữ liệu, hiệu quả thực tế và khả năng đồng hành dài hạn cùng doanh nghiệp.',
    'about.core.intelligent.desc': 'Dẫn dắt bằng dữ liệu, AIoT và insight vận hành để hỗ trợ doanh nghiệp ra quyết định chính xác hơn.',
    'about.core.reliable.desc': 'Xây dựng nền tảng ổn định, bảo mật và đáng tin cậy cho các bài toán enterprise dài hạn.',
    'about.core.sustainable.desc': 'Tối ưu hiệu suất vận hành gắn với tiết kiệm năng lượng, ESG, carbon và phát triển bền vững.',
    
    // Footer
    'footer.quick_links': 'Đường dẫn nhanh',
    'footer.products': 'Sản phẩm',
    'footer.applications': 'Lĩnh vực áp dụng',
    'footer.app1': 'Năng lượng mặt trời áp mái',
    'footer.app2': 'Thang máy',
    'footer.app3': 'Trợ lý AI cho doanh nghiệp',
    'footer.app4': 'Trợ lý AI cho hỏi đáp',
    'footer.contact': 'Thông tin liên hệ',
    'footer.hn_office': 'Văn phòng Hà Nội:',
    'footer.hn_address': 'Tầng 9, Tòa nhà Thiên Niên Kỷ,<br/>Số 4 Quang Trung, Phường Hà Đông, Hà Nội.',
    'footer.hcm_office': 'Văn phòng Hồ Chí Minh:',
    'footer.hcm_address': 'Tầng 6, Tòa nhà DHG, Số 31–33,<br/>Đường 18, Phường Thông Tây Hội,<br/>Thành phố Hồ Chí Minh.',
    'footer.profile': 'Hồ sơ năng lực',
    'footer.download_profile': 'Tải Profile Công ty (PDF)',

    'about.awards.title': 'Giải thưởng & ghi nhận',
    'about.awards.subtitle': 'Dấu mốc ghi nhận năng lực AIoT của Udata',
    'about.awards.p1': 'Năm 2025, Uboard của Udata được vinh danh tại Giải thưởng Sao Khuê 2025 ở hạng mục Sản phẩm, giải pháp, phần mềm, dịch vụ mới. Đây là dấu mốc ghi nhận nỗ lực của Udata trong việc phát triển nền tảng AIoT giúp doanh nghiệp thu thập, giám sát, phân tích và tối ưu dữ liệu vận hành.',
    'about.awards.p2': 'Sự ghi nhận này tiếp thêm động lực để Udata tiếp tục mở rộng hệ sinh thái giải pháp, từ giám sát nhà máy, hợp nhất dữ liệu vận hành đến quản trị carbon và phát triển bền vững.',
    'about.awards.p3': '',
    'about.cta.title': 'Nói bằng dữ liệu. Đồng hành bằng kết quả.',
    'about.cta.subtitle': 'Cùng Udata xây dựng nền tảng vận hành thông minh cho doanh nghiệp của bạn',
    'about.cta.btn1': 'Để lại SĐT',
    'about.cta.btn2': 'Đặt lịch tư vấn',

    // Free Trial Page
    'trial.title': 'Trải nghiệm nền tảng Udata trong 30 phút demo trực tiếp.',
    'trial.subtitle': 'Luôn hoạt động. Luôn chính xác. <br/> Udata - Đồng hành cùng doanh nghiệp trong kỷ nguyên công nghệ và bền vững.',
    'trial.list_title': 'Trong buổi demo 30 phút, chúng tôi sẽ cùng bạn khám phá:',
    'trial.item1.title': 'Tối ưu chi phí và hiệu suất',
    'trial.item1.desc': 'Xem trực tiếp cách hệ thống Udata giúp tiết kiệm điện năng, giảm chi phí vận hành và nâng cao hiệu suất thiết bị.',
    'trial.item2.title': 'Trải nghiệm demo tương tác',
    'trial.item2.desc': 'Dùng thử dashboard thực tế - theo dõi dữ liệu năng lượng, cảnh báo và báo cáo tự động.',
    'trial.item3.title': 'Tư vấn 1:1 cùng chuyên gia',
    'trial.item3.desc': 'Trao đổi về nhu cầu cụ thể của doanh nghiệp bạn, đề xuất giải pháp phù hợp cho từng mô hình vận hành.',
    'trial.item4.title': 'Tài liệu hướng dẫn & bản dùng thử miễn phí 30 ngày',
    'trial.item4.desc': 'Nhận hướng dẫn triển khai chi tiết và quyền truy cập nền tảng Udata trong 30 ngày hoàn toàn miễn phí.',
    'trial.form.title': 'Đăng ký tư vấn và dùng thử miễn phí 30 ngày cùng Udata',
    'trial.form.name': 'Họ và tên',
    'trial.form.name_placeholder': 'Nhập họ và tên',
    'trial.form.company': 'Tên công ty',
    'trial.form.company_placeholder': 'Nhập tên công ty',
    'trial.form.phone': 'Số điện thoại',
    'trial.form.phone_placeholder': 'Nhập số điện thoại',
    'trial.form.email': 'Email',
    'trial.form.email_placeholder': 'Nhập email',
    'trial.form.industry': 'Ngành nghề',
    'trial.form.industry_placeholder': 'Chọn ngành nghề',
    'trial.form.request': 'Nội dung yêu cầu thông tin',
    'trial.form.request_placeholder': 'Hãy mô tả chi tiết yêu cầu của bạn...',
    'trial.form.subscribe': 'Có, tôi muốn Udata chia sẻ cho tôi các tin tức mới nhất về dịch vụ Udata và các chương trình khuyến mãi có liên quan qua email hoặc điện thoại.',
    'trial.form.submit': 'Gửi',
    'trial.form.success': 'Gửi thông tin thành công! Chúng tôi sẽ liên hệ với bạn trong thời gian sớm nhất.',
    'trial.form.error': 'Có lỗi xảy ra. Vui lòng thử lại.',

    // Stub Pages
    'solutions.badge': 'Enterprise Solutions',
    'solutions.title': 'Giải pháp toàn diện cho <br/><span class="text-electric-cyan">chuyển đổi số</span>',
    'solutions.desc': 'Từ giám sát phần cứng đến vận hành AI, Udata cung cấp hệ sinh thái hoàn chỉnh giúp doanh nghiệp tối ưu hóa nguồn lực và bứt phá doanh thu.',
    'solutions.coming_soon': 'Trang chi tiết Giải pháp đang được thiết kế...',

    'usecases.badge': 'Thực tiễn & Ứng dụng',
    'usecases.title': 'Cách khách hàng <br/>ứng dụng <span class="text-electric-cyan">Udata</span>',
    'usecases.desc': 'Khám phá các case study thực tế từ nhiều lĩnh vực: Sản xuất công nghiệp, Y tế, Bán lẻ, và Dịch vụ khách hàng.',
    'usecases.coming_soon': 'Trang Use Cases đang được tổng hợp dữ liệu...',

    'sustainability.badge': 'Tầm nhìn 2050',
    'sustainability.title': 'Phát triển <span class="text-sustain-teal">Bền vững</span> <br/>với Green AI',
    'sustainability.desc': 'Udata cam kết đồng hành cùng doanh nghiệp đo lường phát thải, tối ưu hóa năng lượng và hướng tới mục tiêu Net Zero toàn cầu.',
    'sustainability.coming_soon': 'Báo cáo Phát triển bền vững đang được chuẩn bị...',

    'blog.badge': 'Tin tức & Bài viết',
    'blog.title': 'Khám phá tri thức cùng <br/><span class="text-electric-cyan">Udata Blog</span>',
    'blog.desc': 'Cập nhật những xu hướng công nghệ mới nhất về AI, IoT, chuyển đổi số và phát triển bền vững từ các chuyên gia của chúng tôi.',
    'blog.coming_soon': 'Trang Blog đang được cập nhật nội dung...',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');

  const toggleLang = () => {
    setLang(lang === 'VI' ? 'EN' : 'VI');
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

