"use client";
import React, { createContext, useState, useContext } from 'react';

const translations = {
  EN: {
    // Header
    'nav.about': 'About us',
    'nav.platform': 'Service',
    'nav.build_to_order': 'Build to Order',
    'nav.offshore_dev': 'Offshore Dev Teams',
    'nav.solution': 'Solution',
    'nav.dung_thu': 'Book a Demo',
    'nav.usecase': 'Use case',
    'nav.sustainability': 'Sustainability',
    'nav.blog': 'Blog',
    'nav.resource': 'Careers',
    'nav.bookDemo': 'Book a demo',
    'nav.changeLang': 'Change Language',
    'nav.announcement.badge': 'New update:',
    'nav.announcement.text': 'Discover the new Udata AI ecosystem with superior performance',
    
    // Hero Section
    'hero.badge': 'AIoT PLATFORM FOR GREEN DIGITAL TRANSFORMATION',
    'hero.title.part1': 'Green digital transformation via',
    'hero.title.highlight': 'real-time operational intelligence',
    'hero.subtitle': 'Udata connects AI, IoT, and operational data into a centralized intelligence layer, giving businesses full visibility into production, logistics, finance, and energy flows — optimizing performance, controlling costs, and driving sustainability.',
    'hero.btn.freeTrial': 'Book a Demo',
    'hero.btn.seePlatform': 'Explore Solutions',
    'hero.cta.subtext': 'For manufacturing, logistics, industrial parks and enterprises needing real-time operational optimization',

    // TrustedBy
    'trusted.headline': 'Partnering with enterprises on the journey of operational optimization and sustainable development',
    'trusted.subtext': 'Udata is built for organizations with complex operational systems, where data, performance, costs, and sustainability must be managed through a unified platform.',
    'trusted.title': 'Trusted by Vietnam\'s Leading Enterprises',
    'trusted.stat1.label': 'Enterprises Deployed',
    'trusted.stat2.label': 'Data Points / Day',
    'trusted.stat3.label': 'Average Energy Savings',
    'trusted.stat4.label': 'Platform Uptime SLA',

    // CoreInsight
    'core.badge': 'ENTERPRISE CHALLENGES',
    'core.title.part1': 'Businesses do not lack data. They lack a ',
    'core.title.highlight': 'unified operational intelligence layer.',
    'core.subtitle': 'In many enterprises, data is fragmented across ERP, production, logistics, finance, energy, and internal operational tools. Without a unified connectivity and analytics layer, leadership struggles to see the real-time picture, detect bottlenecks, and accurately measure the effectiveness of digital transformation.',
    'core.feature1.title': 'Data Fragmentation',
    'core.feature1.desc': 'Operational information is divided across multiple systems, departments, and processes, making it hard to gain a unified perspective.',
    'core.feature2.title': 'Lack of Real-time Observation',
    'core.feature2.desc': 'Leaders struggle to simultaneously monitor production, logistics, energy, costs, and performance as issues arise.',
    'core.feature3.title': 'Delayed Decision Making',
    'core.feature3.desc': 'Manual reporting and delayed data lead to missed optimization opportunities, while costs and bottlenecks accumulate.',
    'core.feature4.title': 'ESG & Efficiency Pressure',
    'core.feature4.desc': 'Enterprises need transparent, measurable data to optimize operations, manage emissions, and meet sustainable development standards.',

    // BentoGrid / Ecosystem
    'bento.badge': 'UDATA ECOSYSTEM',
    'bento.title': 'AIoT Ecosystem for Smart Operations',
    'bento.subtitle': 'Udata flexibly connects and analyzes data for specific operational scenarios:<br className="hidden md:block" />from factory monitoring and ESG management to internal knowledge automation.',

    'bento.uboard.label': 'Factory Intelligence',
    'bento.uboard.name': 'Uboard',
    'bento.uboard.title': 'AI + IoT monitoring and factory operation optimization',
    'bento.uboard.desc': 'Monitor equipment data, energy, and performance in real-time to detect anomalies and optimize factory operations.',
    'bento.uboard.cta': 'Explore Uboard',
    'bento.uboard.visualText': 'Realtime monitoring. Operation optimization. Performance enhancement.',

    'bento.ugate.label': 'Central AI Layer',
    'bento.ugate.name': 'Ugate',
    'bento.ugate.title': 'Central AI layer connecting and analyzing enterprise operational data',
    'bento.ugate.desc': 'Consolidate all data sources into a central intelligence layer, empowering leaders with full visibility and instant decision-making.',
    'bento.ugate.cta': 'Learn about Ugate',
    'bento.ugate.visualText': 'From Data Flow to Business Flow',

    'bento.uzero.label': 'Carbon & ESG Management',
    'bento.uzero.name': 'Uzero',
    'bento.uzero.title': 'Carbon and emissions management solution',
    'bento.uzero.desc': 'Emissions measurement and management system, creating a transparent foundation for ESG standards and green growth.',
    'bento.uzero.cta': 'Learn about Uzero',
    'bento.uzero.visualText': 'Carbon Data. ESG Readiness. Sustainable Growth.',

    'bento.mini.label': 'AI Knowledge Assistant',
    'bento.mini.name': 'MiniUgate',
    'bento.mini.title': 'AI chatbot for customer care and internal knowledge processing',
    'bento.mini.desc': 'Automate responses and leverage internal knowledge with AI, accelerating information processing and enhancing customer experience.',
    'bento.mini.cta': 'View MiniUgate',
    'bento.mini.visualText': 'AI Assistant for enterprise knowledge',

    // Workflow
    'workflow.badge': 'DEPLOYMENT WORKFLOW',
    'workflow.title': 'From fragmented data to a smart operational system',
    'workflow.subtitle': 'Udata accompanies businesses from problem surveys, data architecture design, AIoT integration to operation, optimization, and system-wide expansion.',
    'workflow.step1.title': 'Survey & Problem Identification',
    'workflow.step1.desc': 'Analyze operational models, existing systems, required data sources, and enterprise efficiency goals.',
    'workflow.step2.title': 'Data Architecture & AIoT Design',
    'workflow.step2.desc': 'Build data flows, integration points, dashboards, alerts, and metrics suitable for each operational model.',
    'workflow.step3.title': 'Integration & Pilot Deployment',
    'workflow.step3.desc': 'Connect actual devices, systems, and data; verify effectiveness per use case before scaling.',
    'workflow.step4.title': 'Operation, Optimization & Expansion',
    'workflow.step4.desc': 'Monitor results, fine-tune analytical models, and expand solutions to new areas, factories, or processes.',
    'workflow.cta.title': 'Want to know which Udata solution fits your business?',
    'workflow.cta.desc': 'The Udata team will work with you to identify use cases, required data connections, and a suitable deployment roadmap.',
    'workflow.cta.btn': 'Book a demo',

    // CaseStudies
    'case.badge': 'Highlight Use Cases',
    'case.title': 'See how Udata helps enterprises transform',
    'case.c1.cat': 'Manufacturing',
    'case.c1.title': 'Realtime Factory Operation Optimization',
    'case.c1.desc': 'Connect equipment, production lines, and energy data to help factories monitor performance, detect bottlenecks, and improve operational capabilities.',
    'case.c2.cat': 'Energy Optimization',
    'case.c2.title': 'Energy & Operational Cost Control',
    'case.c2.desc': 'Real-time energy consumption tracking, detect waste areas, and support enterprises in optimizing costs based on measured data.',
    'case.c3.cat': 'ESG & Carbon',
    'case.c3.title': 'Building Data Foundation for Sustainability',
    'case.c3.desc': 'Standardize emission data and operational metrics, making enterprises ready for ESG, carbon reporting, and international audit systems.',
    'case.c4.cat': 'Enterprise Operations',
    'case.c4.title': 'Consolidating Fragmented Data into an AI Layer',
    'case.c4.desc': 'Connect data from ERP, logistics, manufacturing, and finance to create a unified view for leadership and support faster decision making.',
    'case.cta': 'View use case',

    // Compliance
    'compliance.badge': 'RELIABILITY & SUSTAINABILITY',
    'compliance.title.line1': 'Enterprise standards for',
    'compliance.title.highlight1': 'secure data',
    'compliance.title.mid': ' and ',
    'compliance.title.highlight2': 'sustainable operations',
    'compliance.subtitle': 'Udata is built with an enterprise mindset: securing operational data, standardizing energy information, supporting ESG/carbon transparency, and meeting international audit requirements in the green digital transformation journey.',
    'compliance.item1.title': 'ISO 27001',
    'compliance.item1.desc': 'Information Security Management',
    'compliance.item2.title': 'ISO 50001',
    'compliance.item2.desc': 'Energy Management',
    'compliance.item3.title': 'GHG Protocol',
    'compliance.item3.desc': 'Emissions Inventory',
    'compliance.item4.title': 'Sao Khue 2025',
    'compliance.item4.desc': 'VINASA Best AIoT',
    'compliance.item5.title': 'COP28',
    'compliance.item5.desc': 'Global Climate Orientation',
    'compliance.item6.title': 'TCFD',
    'compliance.item6.desc': 'Climate Risk Transparency',

    // ExperienceCTA
    'cta.title.part1': 'Ready to turn operational data into a ',
    'cta.title.highlight': 'growth advantage?',
    'cta.subtitle': 'Join Udata in building a central operational intelligence layer for your enterprise — where real-time data becomes the foundation for accurate decisions, higher efficiency, and sustainable development.',
    'cta.input.placeholder': 'Enter your business email',
    'cta.btn.demo': 'Book a Demo',
    'cta.note': 'The Udata team will contact you to advise on a roadmap suited for your operational model.',

    // Careers Page
    'careers.hero.badge': 'WE ARE HIRING',
    'careers.hero.title.part1': 'Join the team building the future of ',
    'careers.hero.title.highlight': 'AI & IoT',
    'careers.hero.subtitle': 'UDATA is looking for young, proactive individuals ready to grow in a practical technology environment.',
    'careers.hero.btn': 'View open roles',

    'careers.why.title': 'Why choose Udata?',
    'careers.why.subtitle': 'We don\'t just build software, we shape how businesses interact with data.',
    'careers.why.1.title': 'Practical Tech Environment',
    'careers.why.1.desc': 'Directly participate in AI, AIoT, Smart Factory, and Digital Transformation projects for manufacturing enterprises.',
    'careers.why.2.title': 'Accelerate Career in AI Era',
    'careers.why.2.desc': 'Work with a high-speed tech team, develop solution mindset and practical B2B skills.',
    'careers.why.3.title': 'Create Real Business Value',
    'careers.why.3.desc': 'Your solutions help businesses optimize operations, improve data utilization, and develop sustainably.',

    'careers.jobs.title': 'Open Positions',
    'careers.jobs.subtitle': 'Find a role that matches your strengths and start your journey at Udata today.',
    'careers.jobs.filter.all': 'All',
    'careers.jobs.filter.sales': 'Sales',
    'careers.jobs.filter.engineering': 'Engineering',
    'careers.jobs.filter.office': 'Office',
    'careers.jobs.filter.marketing': 'Marketing',
    'careers.jobs.btn.view': 'View details',
    'careers.jobs.btn.apply': 'Apply now',

    'careers.process.title': 'Hiring Process',
    'careers.process.subtitle': 'Fair, transparent, and fast is our commitment in the hiring process.',
    'careers.process.1.title': 'Apply',
    'careers.process.1.desc': 'Send your best CV and portfolio to the Talent Acquisition team.',
    'careers.process.2.title': 'Interview',
    'careers.process.2.desc': 'Direct discussion about technical skills and cultural fit with the leadership team.',
    'careers.process.3.title': 'Offer',
    'careers.process.3.desc': 'Welcome to the Udata family to conquer new heights together.',

    'careers.cta.title': 'Can\'t find a suitable position?',
    'careers.cta.subtitle': 'Don\'t hesitate to send us your CV. We are always ready to welcome talents who are eager to contribute.',
    'careers.cta.btn': 'Send Open Application',

    // About Us Page
    'about.badge': 'About Udata',
    'about.hero.subtitle': 'Building an operational intelligence layer for <br /><span class="bg-gradient-to-r from-[#22D3EE] to-[#10F0CB] bg-clip-text text-transparent">green digital transformation</span>',
    'about.intro.title': 'From operational data to sustainable growth',
    'about.intro.p1': 'Udata was created to help enterprises enter the era of green digital transformation through an intelligent AIoT system. We help businesses digitize operational data, control real-time data flows, and optimize performance in line with each organization\'s development strategy.',
    'about.intro.p2': 'Instead of just providing monitoring software, Udata acts as a central operational intelligence layer. The platform connects fragmented operational systems and tools into a unified flow of information that can be analyzed, measured, and transformed into specific actions.',
    'about.intro.p3': 'Through the ecosystem of Ugate, Uboard, Uzero, and MiniUgate, Udata supports businesses to turn operational data into valuable insights, control costs, improve performance, accelerate internal knowledge processing, and build a data foundation for long-term ESG, carbon, and sustainable development.',
    'about.intro.quote': 'Sustainable development is not just a goal. It is a mission Udata shares with every customer.',
    'about.vision.title': 'Vision',
    'about.vision.desc': 'To become the leading green digital transformation platform for businesses in Vietnam and internationally, helping businesses operate intelligently, optimally, and sustainably through AIoT, real-time data, and a centralized operational intelligence layer.',
    'about.mission.title': 'Mission',
    'about.mission.desc': 'Help businesses digitize and control operational data in real-time, optimize performance, accelerate internal knowledge processing, and build a long-term sustainable development foundation.',
    'about.position.title': 'Position',
    'about.position.desc': 'Udata is the central operational intelligence layer that helps businesses connect data, detect bottlenecks, optimize cash flow, improve performance, and drive green digital transformation with measurable results.',
    'about.core.title': 'Core Values',
    'about.core.subtitle': 'Smart technology needs to create real impact',
    'about.core.desc': 'Udata develops technology with an enterprise mindset, focusing on data, real efficiency, and the ability to accompany businesses long-term.',
    'about.core.intelligent.desc': 'Data-driven, AIoT, and operational insights to help businesses make more accurate decisions.',
    'about.core.reliable.desc': 'Build a stable, secure, and reliable platform for long-term enterprise scenarios.',
    'about.core.sustainable.desc': 'Optimize operational performance coupled with energy saving, ESG, carbon, and sustainable development.',
    
    // Footer
    'footer.quick_links': 'Quick Links',
    'footer.products': 'Products',
    'footer.applications': 'Applications',
    'footer.app1': 'Rooftop Solar',
    'footer.app2': 'Elevators',
    'footer.app3': 'Enterprise AI Assistant',
    'footer.app4': 'Q&A AI Assistant',
    'footer.contact': 'Contact Information',
    'footer.hn_office': 'Hanoi Office:',
    'footer.hn_address': '9th Floor, Millennium Building,<br/>4 Quang Trung, Ha Dong District, Hanoi.',
    'footer.hcm_office': 'Ho Chi Minh Office:',
    'footer.hcm_address': '6th Floor, DHG Building, 31-33<br/>Street 18, Thong Tay Hoi Ward,<br/>Ho Chi Minh City.',
    'footer.profile': 'Company Profile',
    'footer.download_profile': 'Download Company Profile (PDF)',

    'about.awards.title': 'Awards & Recognition',
    'about.awards.subtitle': "A milestone recognizing Udata's AIoT capabilities",
    'about.awards.p1': 'In 2025, Udata\'s Uboard was honored at the Sao Khue Awards 2025 in the category of New products, solutions, software, and services. This is a milestone recognizing Udata\'s efforts in developing an AIoT platform that helps businesses collect, monitor, analyze, and optimize operational data.',
    'about.awards.p2': 'This recognition provides further motivation for Udata to continue expanding its ecosystem of solutions, from factory monitoring and operational data consolidation to carbon management and sustainable development.',
    'about.awards.p3': '',
    'about.cta.title': 'Speak with data. Partner for results.',
    'about.cta.subtitle': 'Build a smart operational platform for your business with Udata',
    'about.cta.btn1': 'Explore Solutions',
    'about.cta.btn2': 'Book a Demo',

    // Free Trial Page
    'trial.title': 'Experience the Udata platform with a 30-minute live demo.',
    'trial.subtitle': 'Always on. Always accurate. <br /> Udata - Accompanying businesses in the era of technology and sustainability.',
    'trial.list_title': 'In the 30-minute demo, we will explore with you:',
    'trial.item1.title': 'Cost and performance optimization',
    'trial.item1.desc': 'See firsthand how the Udata system helps save energy, reduce operating costs, and improve equipment performance.',
    'trial.item2.title': 'Interactive demo experience',
    'trial.item2.desc': 'Try out actual dashboards - monitor energy data, alerts, and automated reports.',
    'trial.item3.title': '1:1 expert consultation',
    'trial.item3.desc': 'Discuss your specific business needs and receive tailored solution recommendations.',
    'trial.item4.title': 'Guides & 30-day free trial',
    'trial.item4.desc': 'Receive detailed implementation guides and 30 days of full access to the Udata platform for free.',
    'trial.form.title': 'Register for a consultation and 30-day free trial',
    'trial.form.name': 'Full Name',
    'trial.form.name_placeholder': 'Enter your full name',
    'trial.form.company': 'Company Name',
    'trial.form.company_placeholder': 'Enter your company name',
    'trial.form.phone': 'Phone Number',
    'trial.form.phone_placeholder': 'Enter your phone number',
    'trial.form.email': 'Email Address',
    'trial.form.email_placeholder': 'Enter your email',
    'trial.form.industry': 'Industry',
    'trial.form.industry_placeholder': 'Select industry',
    'trial.form.request': 'Request details',
    'trial.form.request_placeholder': 'Please describe what you are looking for...',
    'trial.form.subscribe': 'Yes, I want to receive the latest news about Udata services and promotions via email or phone.',
    'trial.form.submit': 'Submit',
    'trial.form.success': 'Registration successful! We will contact you shortly.',
    'trial.form.error': 'An error occurred. Please try again.',

    // Stub Pages
    'solutions.badge': 'Enterprise Solutions',
    'solutions.title': 'Comprehensive Solutions for <br/><span class="text-electric-cyan">digital transformation</span>',
    'solutions.desc': 'From hardware monitoring to AI operation, Udata provides a complete ecosystem to help businesses optimize resources and breakthrough revenue.',
    'solutions.coming_soon': 'Solution details page is being designed...',

    'usecases.badge': 'PRACTICE LEADS THE WAY',
    'usecases.title': 'How enterprises use Udata <br className="hidden md:block" />for <span class="text-[#22D3EE] drop-shadow-[0_0_15px_rgba(34,211,238,0.3)]">smart operations</span>',
    'usecases.desc': 'A list of practical use cases from multiple enterprises across various industries. Each case reflects a specific data problem, and how Udata connects, processes, and creates tangible operational value.',
    'usecases.hero.btn1': 'Explore use cases',
    'usecases.hero.btn2': 'Contact for consultation',
    'usecases.hero.info': 'Data, scenarios, and results here are anonymous or aggregated closely to real deployments, helping businesses learn quickly from practical experience and apply effectively.',
    
    'usecases.steps.title': 'Every use case starts with a specific data problem',
    'usecases.steps.desc': 'Udata helps enterprises connect fragmented data, clean and standardize it, then exploit it to solve real operational problems.',
    'usecases.steps.1.title': '1. Connect and Collect',
    'usecases.steps.1.desc': 'Connect all data sources (operations, equipment, sensors, internal systems, external...) in real-time or according to schedule.',
    'usecases.steps.2.title': '2. Standardize and Clean',
    'usecases.steps.2.desc': 'Clean, standardize, remove duplicates and normalize data to ensure quality and readiness for in-depth analysis.',
    'usecases.steps.3.title': '3. Model & Analyze',
    'usecases.steps.3.desc': 'Apply AI, analyze and model data to discover patterns, predict and generate valuable information.',
    'usecases.steps.4.title': '4. Metrics & Tracking',
    'usecases.steps.4.desc': 'Turn data into visual metrics and reports, supporting fast decision making and timely action.',

    'usecases.grid.title': 'Highlight Use Cases',
    'usecases.grid.desc': 'Selected use cases from multiple industries. You can filter by Udata products to see examples that best fit your needs.',
    'usecases.grid.filter.all': 'All',
    
    'usecases.metrics.title': 'Business metrics you can track',
    'usecases.metrics.desc': 'Focus on core operational & business metrics that can be measured and improved through data.',
    'usecases.metrics.1.title': 'Operational Performance',
    'usecases.metrics.1.items': '• OEE, productivity, output|• Defect, scrap rate|• Downtime',
    'usecases.metrics.2.title': 'Supply Chain & Inventory',
    'usecases.metrics.2.items': '• Inventory turnover ratio|• On-time delivery rate|• Order cycle time',
    'usecases.metrics.3.title': 'Energy & Resources',
    'usecases.metrics.3.items': '• Electricity, water, heat consumption|• Resource utilization efficiency|• Waste detection',
    'usecases.metrics.4.title': 'Carbon & Environment',
    'usecases.metrics.4.items': '• CO₂e emissions|• Environmental compliance rate|• Consolidated ESG index',
    'usecases.metrics.5.title': 'Finance & Business',
    'usecases.metrics.5.items': '• Revenue, profit|• Operating costs|• Profit margin',

    'usecases.cta.title': 'Which operational problem are you trying to solve?',
    'usecases.cta.desc': 'Let Udata accompany you in building a data and analysis system tailored to your business reality.',
    'usecases.cta.btn1': 'Request Consultation',
    'usecases.cta.btn2': 'Solution Documents',

    'sustainability.badge': 'Vision 2050',
    'sustainability.title': '<span class="text-sustain-teal">Sustainable</span> Development <br/>with Green AI',
    'sustainability.desc': 'Udata is committed to accompanying businesses in measuring emissions, optimizing energy, and aiming for the global Net Zero goal.',
    'sustainability.coming_soon': 'Sustainability Report is being prepared...',

    'blog.badge': 'News & Articles',
    'blog.title': 'Discover knowledge with <br/><span class="text-electric-cyan">Udata Blog</span>',
    'blog.desc': 'Catch up on the latest technology trends in AI, IoT, digital transformation, and sustainable development from our experts.',
    'blog.coming_soon': 'Blog page is being updated with content...',

    // Build to Order Page
    'bto.hero.badge': 'CUSTOM SOFTWARE DEVELOPMENT SERVICES',
    'bto.hero.title': 'Build to Order',
    'bto.hero.subtitle': 'Let us handle the heavy lifting. Custom software solutions tailored to your unique business needs.',
    'bto.hero.btn1': 'Book an online consultation',
    'bto.hero.btn2': 'View Portfolio',
    
    'bto.benefits.badge': 'BENEFITS OF SOFTWARE OUTSOURCING',
    'bto.benefits.title': 'Why Build Your Software With Udata?',
    'bto.benefits.desc': 'Every project is different and that\'s exactly why we\'re here. Our Team thrives on complex challenges.',
    'bto.benefits.b1.title': 'Kickoff in 2-4 Weeks',
    'bto.benefits.b1.desc': 'We quickly assemble the right talent to match your project needs.',
    'bto.benefits.b2.title': 'End-to-End Delivery',
    'bto.benefits.b2.desc': 'Beyond just development, we handle UI/UX, testing, and deployment.',
    'bto.benefits.b3.title': 'Clear Communication',
    'bto.benefits.b3.desc': 'Direct channels with engineers ensure your vision is realized accurately.',
    'bto.benefits.b4.title': 'Senior Experts Embedded',
    'bto.benefits.b4.desc': 'Senior technical leaders oversee architecture and code quality in every project.',
    
    'bto.process.badge': 'OUR PROCESS',
    'bto.process.title': 'Our Custom Software Development Process',
    'bto.process.desc': 'We deliver solutions aligned to scope, timeline, and budget within 95 percent of estimates.',
    'bto.process.s1.title': 'Discovery',
    'bto.process.s1.desc': 'We dive deep into your domain to align objectives, clarify scope, and surface risks.',
    'bto.process.s2.title': 'UI/UX Design',
    'bto.process.s2.desc': 'We transform concepts into polished, user-friendly UI/UX, validating flows with stakeholders.',
    'bto.process.s3.title': 'Custom Development',
    'bto.process.s3.desc': 'We release through focused sprints with daily tracking and transparent progress.',
    'bto.process.s4.title': 'Testing & QA',
    'bto.process.s4.desc': 'Features undergo comprehensive automated and regression tests for stable releases.',
    
    'bto.why.badge': 'WHEN ONE-SIZE DOESN\'T FIT',
    'bto.why.title': 'Why Choose Udata?',
    'bto.why.w1.title': 'Scalable & Secure',
    'bto.why.w1.desc': 'Architectures designed to grow with your user base and protect sensitive data.',
    'bto.why.w2.title': 'Real-Time Collaboration',
    'bto.why.w2.desc': 'Daily standups, sprint reviews, and live demos keep you in the loop.',
    'bto.why.w3.title': 'High-Quality Builds',
    'bto.why.w3.desc': 'We prioritize clean code, test coverage, and maintainable systems.',
    
    'bto.faq.badge': 'FAQ',
    'bto.faq.title': 'Frequently Asked Questions',
    'bto.faq.desc': 'Everything you need to know about our custom software development services.',
    'bto.faq.q1.q': 'How long does custom software take to launch?',
    'bto.faq.q1.a': 'Depending on complexity, an MVP typically takes 2-3 months, while full enterprise solutions take 6+ months.',
    'bto.faq.q2.q': 'Are there any hidden costs?',
    'bto.faq.q2.a': 'No. We provide transparent estimates and any scope changes are approved by you before incurring costs.',
    'bto.faq.q3.q': 'How do you choose the right tech stack?',
    'bto.faq.q3.a': 'We evaluate your performance needs, scalability goals, team expertise, and budget to select the optimal stack.',

    // Offshore Dev Teams Page
    'odc.hero.badge': 'OFFSHORE DEVELOPMENT CENTER',
    'odc.hero.title': 'Offshore Development Teams',
    'odc.hero.subtitle': 'Unlock Offshore Development Excellence. Build your dedicated scalable team with secure facilities and senior expertise.',
    'odc.hero.btn1': 'Book an online consultation',
    'odc.hero.btn2': 'View Portfolio',
    
    'odc.benefits.badge': 'BENEFITS OF OFFSHORE SOFTWARE DEVELOPMENT',
    'odc.benefits.title': 'Why Build Your Dedicated Team With Udata?',
    'odc.benefits.desc': 'Leverage our established infrastructure, top-tier talent, and proven processes to scale your engineering capacity rapidly.',
    'odc.benefits.b1.title': 'Knowledge Transfer',
    'odc.benefits.b1.desc': 'Seamless onboarding and continuous knowledge sharing ensures your ODC operates as a true extension.',
    'odc.benefits.b2.title': 'Workforce Stability',
    'odc.benefits.b2.desc': 'Scale your team up or down based on your roadmap without the hiring hassle and employee turnover risks.',
    'odc.benefits.b3.title': 'Security & IP Protection',
    'odc.benefits.b3.desc': 'Strict security policies and NDAs ensure your intellectual property and data remain completely safe.',
    'odc.benefits.b4.title': 'Commit To Excellence',
    'odc.benefits.b4.desc': 'Quality is embedded at every stage, from recruitment to final code delivery and maintenance.',
    
    'odc.tech.badge': 'CORE TECHNOLOGIES',
    'odc.tech.title': 'Our Technical Expertise',
    'odc.tech.desc': 'We align stack choices with your goals, scale, and budget—evaluating performance, security, and cloud costs.',
    
    'odc.why.badge': 'REASON TO GO WITH UDATA SOLUTION',
    'odc.why.title': 'Why Choose Our ODC Model',
    'odc.why.w1.title': 'Build ONE TEAM With Clients',
    'odc.why.w1.desc': 'We integrate deeply into your culture, working as a seamless extension of your in-house team with shared goals.',
    'odc.why.w2.title': 'Companionship',
    'odc.why.w2.desc': 'We don\'t just code; we partner with you on business transformation and long-term strategic growth.',
    'odc.why.w3.title': 'Cost-Effectiveness',
    'odc.why.w3.desc': 'Optimize your development budget with transparent pricing models and efficient offshore talent pools.',
    
    'odc.faq.badge': 'FAQ',
    'odc.faq.title': 'Frequently Asked Questions',
    'odc.faq.desc': 'Everything you need to know about our Offshore Development Center services.',
    'odc.faq.q1.q': 'What is the size of your development team?',
    'odc.faq.q1.a': 'We have a deep pool of over 500 engineers, allowing us to build teams from 5 to 50+ members based on your needs.',
    'odc.faq.q2.q': 'How do you ensure effective communication?',
    'odc.faq.q2.a': 'We align time zones, establish daily standups, and utilize robust PM tools to ensure transparent, continuous communication.',
    'odc.faq.q3.q': 'What security measures do you have in place?',
    'odc.faq.q3.a': 'We enforce strict NDA agreements, secure network protocols, ISO-certified processes, and comprehensive data protection policies.',
  },
  VI: {
    // Header
    'nav.about': 'Về chúng tôi',
    'nav.platform': 'Dịch vụ',
    'nav.build_to_order': 'Phát triển theo yêu cầu',
    'nav.offshore_dev': 'Trung tâm Offshore (ODC)',
    'nav.solution': 'Giải pháp',
    'nav.dung_thu': 'Dùng thử',
    'nav.usecase': 'Tình huống ứng dụng',
    'nav.sustainability': 'Phát triển bền vững',
    'nav.blog': 'Bài viết',
    'nav.resource': 'Tuyển dụng',
    'nav.bookDemo': 'Đặt lịch Demo',
    'nav.changeLang': 'Đổi ngôn ngữ',
    'nav.announcement.badge': 'Mới cập nhật:',
    'nav.announcement.text': 'Khám phá hệ sinh thái AIoT cho vận hành thông minh và chuyển đổi số xanh',
    
    // Hero Section
    'hero.badge': 'NỀN TẢNG AIoT CHO CHUYỂN ĐỔI SỐ XANH',
    'hero.title.part1': 'Chuyển đổi số xanh bằng',
    'hero.title.highlight': 'trí tuệ vận hành thời gian thực',
    'hero.subtitle': 'Udata kết nối AI, IoT và dữ liệu vận hành vào một lớp trí tuệ tập trung, giúp doanh nghiệp nhìn thấy toàn bộ dòng chảy<br className="hidden md:block"/>sản xuất, kho vận, tài chính và năng lượng — từ đó tối ưu hiệu suất, kiểm soát chi phí và phát triển bền vững.',
    'hero.btn.freeTrial': 'Đặt lịch Demo',
    'hero.btn.seePlatform': 'Khám phá giải pháp',
    'hero.cta.subtext': 'Dành cho doanh nghiệp sản xuất, logistics, khu công nghiệp và enterprise cần tối ưu vận hành bằng dữ liệu realtime',

    // TrustedBy
    'trusted.headline': 'Đồng hành cùng doanh nghiệp trong hành trình tối ưu vận hành và phát triển bền vững',
    'trusted.subtext': 'Udata được xây dựng cho các tổ chức có hệ thống vận hành phức tạp, nơi dữ liệu, hiệu suất, chi phí và tính bền vững cần được quản trị bằng một nền tảng thống nhất.',
    'trusted.title': 'Đồng hành cùng doanh nghiệp trong hành trình tối ưu vận hành và phát triển bền vững',
    'trusted.stat1.label': 'Doanh nghiệp đã triển khai',
    'trusted.stat2.label': 'Điểm dữ liệu / Ngày',
    'trusted.stat3.label': 'Tiết kiệm năng lượng trung bình',
    'trusted.stat4.label': 'SLA hoạt động của nền tảng',

    // CoreInsight
    'core.badge': 'BÀI TOÁN DOANH NGHIỆP',
    'core.title.part1': 'Dữ liệu không thiếu. Doanh nghiệp thiếu một ',
    'core.title.highlight': 'lớp trí tuệ vận hành tập trung.',
    'core.subtitle': 'Trong nhiều doanh nghiệp, dữ liệu đang nằm rời rạc giữa ERP, sản xuất, kho vận, tài chính, năng lượng và các công cụ vận hành nội bộ. Khi thiếu một lớp kết nối và phân tích thống nhất, ban lãnh đạo khó nhìn thấy bức tranh realtime, khó phát hiện điểm nghẽn và khó đo lường chính xác hiệu quả chuyển đổi số.',
    'core.feature1.title': 'Dữ liệu phân mảnh',
    'core.feature1.desc': 'Thông tin vận hành bị chia cắt giữa nhiều hệ thống, phòng ban và quy trình, khiến doanh nghiệp khó có một góc nhìn thống nhất.',
    'core.feature2.title': 'Thiếu quan sát realtime',
    'core.feature2.desc': 'Lãnh đạo khó theo dõi đồng thời sản xuất, kho vận, năng lượng, chi phí và hiệu suất ngay khi vấn đề phát sinh.',
    'core.feature3.title': 'Quyết định đến chậm',
    'core.feature3.desc': 'Báo cáo thủ công và dữ liệu trễ khiến cơ hội tối ưu bị bỏ lỡ, trong khi chi phí và điểm nghẽn tiếp tục tích lũy.',
    'core.feature4.title': 'Áp lực ESG & hiệu quả',
    'core.feature4.desc': 'Doanh nghiệp cần dữ liệu minh bạch, đo lường được để tối ưu vận hành, quản trị phát thải và đáp ứng các tiêu chuẩn phát triển bền vững.',

    // BentoGrid / Ecosystem
    'bento.badge': 'HỆ SINH THÁI UDATA',
    'bento.title': 'Hệ sinh thái AIoT cho vận hành thông minh',
    'bento.subtitle': 'Udata linh hoạt kết nối và tối ưu dữ liệu theo bài toán vận hành thực tế:<br className="hidden md:block" />từ giám sát nhà máy, quản trị ESG đến tự động hóa tri thức nội bộ.',

    'bento.uboard.label': 'Trí tuệ Nhà máy',
    'bento.uboard.name': 'Uboard',
    'bento.uboard.title': 'AI + IoT giám sát và tối ưu vận hành nhà máy',
    'bento.uboard.desc': 'Theo dõi dữ liệu thiết bị, năng lượng và hiệu suất theo thời gian thực để phát hiện bất thường và tối ưu vận hành nhà máy.',
    'bento.uboard.cta': 'Khám phá Uboard',
    'bento.uboard.visualText': 'Giám sát realtime. Tối ưu vận hành. Nâng cao hiệu suất.',

    'bento.ugate.label': 'Lớp AI Trung tâm',
    'bento.ugate.name': 'Ugate',
    'bento.ugate.title': 'Lớp AI trung tâm kết nối và phân tích dữ liệu vận hành doanh nghiệp',
    'bento.ugate.desc': 'Hợp nhất mọi nguồn dữ liệu (ERP, sản xuất, tài chính...) vào một lớp trí tuệ trung tâm, giúp lãnh đạo nhìn thấu toàn cảnh và ra quyết định tức thời.',
    'bento.ugate.cta': 'Tìm hiểu Ugate',
    'bento.ugate.visualText': 'From Data Flow to Business Flow',

    'bento.uzero.label': 'Quản trị Carbon & ESG',
    'bento.uzero.name': 'Uzero',
    'bento.uzero.title': 'Giải pháp quản trị carbon và phát thải',
    'bento.uzero.desc': 'Hệ thống đo lường và quản trị dữ liệu phát thải, tạo nền tảng minh bạch đáp ứng tiêu chuẩn ESG và lộ trình tăng trưởng xanh.',
    'bento.uzero.cta': 'Tìm hiểu Uzero',
    'bento.uzero.visualText': 'Carbon Data. ESG Readiness. Sustainable Growth.',

    'bento.mini.label': 'Trợ lý Tri thức AI',
    'bento.mini.name': 'MiniUgate',
    'bento.mini.title': 'AI chatbot cho chăm sóc khách hàng và xử lý tri thức nội bộ',
    'bento.mini.desc': 'Tự động hóa phản hồi và khai thác tri thức nội bộ bằng AI, giúp tăng tốc xử lý thông tin và nâng cao trải nghiệm khách hàng.',
    'bento.mini.cta': 'Xem MiniUgate',
    'bento.mini.visualText': 'Trợ lý AI cho tri thức doanh nghiệp',

    // Workflow
    'workflow.badge': 'QUY TRÌNH TRIỂN KHAI',
    'workflow.title': 'Từ dữ liệu phân mảnh đến hệ thống vận hành thông minh',
    'workflow.subtitle': 'Udata đồng hành cùng doanh nghiệp từ khảo sát bài toán, thiết kế kiến trúc dữ liệu, tích hợp AIoT đến vận hành, tối ưu và mở rộng trên toàn hệ thống.',
    'workflow.step1.title': 'Khảo sát & xác định bài toán',
    'workflow.step1.desc': 'Phân tích mô hình vận hành, hệ thống hiện có, nguồn dữ liệu cần kết nối và mục tiêu hiệu quả của doanh nghiệp.',
    'workflow.step2.title': 'Thiết kế kiến trúc dữ liệu & AIoT',
    'workflow.step2.desc': 'Xây dựng luồng dữ liệu, điểm tích hợp, dashboard, cảnh báo và bộ chỉ số đo lường phù hợp với từng mô hình vận hành.',
    'workflow.step3.title': 'Tích hợp & triển khai thử nghiệm',
    'workflow.step3.desc': 'Kết nối thiết bị, hệ thống và dữ liệu thực tế; kiểm chứng hiệu quả theo từng use case trước khi mở rộng.',
    'workflow.step4.title': 'Vận hành, tối ưu & mở rộng',
    'workflow.step4.desc': 'Theo dõi kết quả, tinh chỉnh mô hình phân tích và mở rộng giải pháp sang các khu vực, nhà máy hoặc quy trình mới.',
    'workflow.cta.title': 'Bạn muốn biết Udata phù hợp với bài toán nào của doanh nghiệp?',
    'workflow.cta.desc': 'Đội ngũ Udata sẽ cùng bạn xác định use case, dữ liệu cần kết nối và lộ trình triển khai phù hợp.',
    'workflow.cta.btn': 'Đặt lịch demo',

    // CaseStudies
    'case.badge': 'Tình huống ứng dụng nổi bật',
    'case.title': 'Xem cách Udata giúp các doanh nghiệp chuyển đổi',
    'case.c1.cat': 'Manufacturing',
    'case.c1.title': 'Tối ưu vận hành nhà máy bằng dữ liệu realtime',
    'case.c1.desc': 'Kết nối dữ liệu thiết bị, dây chuyền và năng lượng để giúp nhà máy theo dõi hiệu suất, phát hiện điểm nghẽn và nâng cao năng lực vận hành.',
    'case.c2.cat': 'Energy Optimization',
    'case.c2.title': 'Kiểm soát năng lượng và chi phí vận hành',
    'case.c2.desc': 'Theo dõi tiêu thụ năng lượng theo thời gian thực, phát hiện khu vực lãng phí và hỗ trợ doanh nghiệp tối ưu chi phí dựa trên dữ liệu đo lường được.',
    'case.c3.cat': 'ESG & Carbon',
    'case.c3.title': 'Xây dựng nền tảng dữ liệu cho phát triển bền vững',
    'case.c3.desc': 'Chuẩn hóa dữ liệu phát thải và chỉ số vận hành, giúp doanh nghiệp sẵn sàng hơn cho ESG, carbon reporting và các hệ thống audit quốc tế.',
    'case.c4.cat': 'Enterprise Operations',
    'case.c4.title': 'Hợp nhất dữ liệu phân mảnh thành một lớp trí tuệ vận hành',
    'case.c4.desc': 'Kết nối dữ liệu từ ERP, kho vận, sản xuất và tài chính để tạo góc nhìn thống nhất cho ban lãnh đạo và hỗ trợ ra quyết định nhanh hơn.',
    'case.cta': 'Xem tình huống ứng dụng',

    // Compliance
    'compliance.badge': 'TIN CẬY & PHÁT TRIỂN BỀN VỮNG',
    'compliance.title.line1': 'Chuẩn mực enterprise cho',
    'compliance.title.highlight1': 'dữ liệu an toàn',
    'compliance.title.mid': ' và ',
    'compliance.title.highlight2': 'vận hành bền vững',
    'compliance.subtitle': 'Udata được xây dựng theo tư duy enterprise: bảo mật dữ liệu vận hành, chuẩn hóa thông tin năng lượng, hỗ trợ minh bạch ESG/carbon và đáp ứng các yêu cầu audit quốc tế trong hành trình chuyển đổi số xanh.',
    'compliance.item1.title': 'ISO 27001',
    'compliance.item1.desc': 'Quản trị an toàn thông tin',
    'compliance.item2.title': 'ISO 50001',
    'compliance.item2.desc': 'Quản trị năng lượng',
    'compliance.item3.title': 'GHG Protocol',
    'compliance.item3.desc': 'Kiểm kê Khí thải',
    'compliance.item4.title': 'Sao Khuê 2025',
    'compliance.item4.desc': 'AIoT xuất sắc nhất từ VINASA',
    'compliance.item5.title': 'COP28',
    'compliance.item5.desc': 'Định hướng khí hậu toàn cầu',
    'compliance.item6.title': 'TCFD',
    'compliance.item6.desc': 'Minh bạch rủi ro khí hậu',

    // ExperienceCTA
    'cta.title.part1': 'Sẵn sàng biến dữ liệu vận hành thành ',
    'cta.title.highlight': 'lợi thế tăng trưởng?',
    'cta.subtitle': 'Hãy cùng Udata xây dựng lớp trí tuệ vận hành trung tâm cho doanh nghiệp của bạn — nơi dữ liệu realtime trở thành nền tảng cho quyết định chính xác, hiệu suất cao hơn và phát triển bền vững hơn.',
    'cta.input.placeholder': 'Nhập email doanh nghiệp của bạn',
    'cta.btn.demo': 'Đặt lịch Demo',
    'cta.note': 'Đội ngũ Udata sẽ liên hệ để tư vấn lộ trình phù hợp với mô hình vận hành của doanh nghiệp.',

    // Careers Page
    'careers.hero.badge': 'ĐANG TUYỂN DỤNG',
    'careers.hero.title.part1': 'Gia nhập đội ngũ kiến tạo tương lai ',
    'careers.hero.title.highlight': 'AI & IoT',
    'careers.hero.subtitle': 'UDATA đang tìm kiếm những nhân sự trẻ, chủ động và sẵn sàng phát triển trong môi trường công nghệ thực chiến.',
    'careers.hero.btn': 'Xem các vị trí trống',

    'careers.why.title': 'Tại sao chọn Udata?',
    'careers.why.subtitle': 'Chúng tôi không chỉ xây dựng phần mềm, chúng tôi định hình cách doanh nghiệp tương tác với dữ liệu.',
    'careers.why.1.title': 'Môi trường Công nghệ Thực chiến',
    'careers.why.1.desc': 'Tham gia trực tiếp vào các dự án AI, AIoT, Smart Factory và Chuyển đổi số cho doanh nghiệp sản xuất.',
    'careers.why.2.title': 'Tăng tốc Sự nghiệp trong Kỷ nguyên AI',
    'careers.why.2.desc': 'Làm việc cùng đội ngũ công nghệ tốc độ cao, phát triển tư duy solution và kỹ năng thực chiến B2B.',
    'careers.why.3.title': 'Tạo ra Giá trị cho Doanh nghiệp Thực',
    'careers.why.3.desc': 'Các giải pháp của bạn giúp doanh nghiệp tối ưu vận hành, nâng cao hiệu suất sử dụng dữ liệu và phát triển bền vững.',

    'careers.jobs.title': 'Vị trí đang tuyển',
    'careers.jobs.subtitle': 'Tìm thấy vị trí phù hợp với thế mạnh của bạn và bắt đầu hành trình tại Udata ngay hôm nay.',
    'careers.jobs.filter.all': 'Tất cả',
    'careers.jobs.filter.sales': 'Kinh doanh',
    'careers.jobs.filter.engineering': 'Engineering',
    'careers.jobs.filter.office': 'Văn phòng',
    'careers.jobs.filter.marketing': 'Marketing',
    'careers.jobs.btn.view': 'Xem chi tiết',
    'careers.jobs.btn.apply': 'Ứng tuyển ngay',

    'careers.process.title': 'Quy trình tuyển dụng',
    'careers.process.subtitle': 'Công bằng, minh bạch và nhanh chóng là cam kết của chúng tôi trong quy trình tuyển dụng.',
    'careers.process.1.title': 'Ứng tuyển',
    'careers.process.1.desc': 'Gửi CV và portfolio ấn tượng nhất của bạn cho đội ngũ Talent Acquisition.',
    'careers.process.2.title': 'Phỏng vấn',
    'careers.process.2.desc': 'Trao đổi trực tiếp về kỹ năng chuyên môn và sự phù hợp về văn hóa với đội ngũ lãnh đạo.',
    'careers.process.3.title': 'Nhận Offer',
    'careers.process.3.desc': 'Chào mừng bạn gia nhập đại gia đình Udata để cùng nhau chinh phục những đỉnh cao mới.',

    'careers.cta.title': 'Chưa thấy vị trí phù hợp?',
    'careers.cta.subtitle': 'Đừng ngần ngại gửi CV của bạn cho chúng tôi. Chúng tôi luôn sẵn lòng chào đón những nhân tài khao khát cống hiến.',
    'careers.cta.btn': 'Gửi CV Tự do',

    // About Us Page
    'about.badge': 'Về Udata',
    'about.hero.subtitle': 'Kiến tạo lớp trí tuệ vận hành cho <br /> <span class="bg-gradient-to-r from-[#22D3EE] to-[#10F0CB] bg-clip-text text-transparent">chuyển đổi số xanh</span>',
    'about.intro.title': 'Từ dữ liệu vận hành đến tăng trưởng bền vững',
    'about.intro.p1': 'Udata được tạo ra nhằm giúp doanh nghiệp bước vào kỷ nguyên chuyển đổi số xanh thông qua hệ thống AIoT thông minh. Chúng tôi giúp doanh nghiệp số hóa dữ liệu vận hành, kiểm soát dòng dữ liệu theo thời gian thực và tối ưu hiệu suất phù hợp với chiến lược phát triển của từng tổ chức.',
    'about.intro.p2': 'Thay vì chỉ cung cấp một phần mềm giám sát, Udata đóng vai trò như một lớp trí tuệ vận hành trung tâm. Nền tảng giúp kết nối các hệ thống và công cụ vận hành đang phân mảnh thành một dòng thông tin thống nhất, có thể phân tích, đo lường và chuyển hóa thành hành động cụ thể.',
    'about.intro.p3': 'Thông qua hệ sinh thái Ugate, Uboard, Uzero và MiniUgate, Udata hỗ trợ doanh nghiệp biến dữ liệu vận hành thành insight có giá trị, kiểm soát chi phí, nâng cao hiệu suất, tăng tốc xử lý tri thức nội bộ và xây dựng nền tảng dữ liệu phục vụ ESG, carbon và phát triển bền vững trong dài hạn.',
    'about.intro.quote': 'Phát triển bền vững không chỉ là mục tiêu. Đó là sứ mệnh Udata chia sẻ cùng từng khách hàng.',
    'about.vision.title': 'Tầm nhìn',
    'about.vision.desc': 'Trở thành nền tảng chuyển đổi số xanh hàng đầu cho doanh nghiệp tại Việt Nam và quốc tế, giúp doanh nghiệp vận hành thông minh, tối ưu và bền vững thông qua AIoT, dữ liệu realtime và lớp trí tuệ vận hành tập trung.',
    'about.mission.title': 'Sứ mệnh',
    'about.mission.desc': 'Giúp doanh nghiệp số hóa và kiểm soát dữ liệu vận hành theo thời gian thực, tối ưu hiệu suất, tăng tốc xử lý tri thức nội bộ và xây dựng nền tảng phát triển bền vững dài hạn.',
    'about.position.title': 'Định vị',
    'about.position.desc': 'Udata là lớp trí tuệ vận hành trung tâm giúp doanh nghiệp kết nối dữ liệu, phát hiện điểm nghẽn, tối ưu dòng tiền, nâng cao hiệu suất và thúc đẩy chuyển đổi số xanh bằng những kết quả có thể đo lường.',
    'about.core.title': 'Giá trị cốt lõi',
    'about.core.subtitle': 'Công nghệ thông minh cần tạo ra tác động thực tế',
    'about.core.desc': 'Udata phát triển công nghệ với tư duy enterprise, tập trung vào dữ liệu, hiệu quả thực tế và khả năng đồng hành dài hạn cùng doanh nghiệp.',
    'about.core.intelligent.desc': 'Dẫn dắt bằng dữ liệu, AIoT và insight vận hành để hỗ trợ doanh nghiệp ra quyết định chính xác hơn.',
    'about.core.reliable.desc': 'Xây dựng nền tảng ổn định, bảo mật và đáng tin cậy cho các bài toán enterprise dài hạn.',
    'about.core.sustainable.desc': 'Tối ưu hiệu suất vận hành gắn với tiết kiệm năng lượng, ESG, carbon và phát triển bền vững.',
    
    // Footer
    'footer.quick_links': 'Đường dẫn nhanh',
    'footer.products': 'Sản phẩm',
    'footer.applications': 'Lĩnh vực áp dụng',
    'footer.app1': 'Năng lượng mặt trời áp mái',
    'footer.app2': 'Thang máy',
    'footer.app3': 'Trợ lý AI cho doanh nghiệp',
    'footer.app4': 'Trợ lý AI cho hỏi đáp',
    'footer.contact': 'Thông tin liên hệ',
    'footer.hn_office': 'Văn phòng Hà Nội:',
    'footer.hn_address': 'Tầng 9, Tòa nhà Thiên Niên Kỷ,<br/>Số 4 Quang Trung, Phường Hà Đông, Hà Nội.',
    'footer.hcm_office': 'Văn phòng Hồ Chí Minh:',
    'footer.hcm_address': 'Tầng 6, Tòa nhà DHG, Số 31–33,<br/>Đường 18, Phường Thông Tây Hội,<br/>Thành phố Hồ Chí Minh.',
    'footer.profile': 'Hồ sơ năng lực',
    'footer.download_profile': 'Tải Profile Công ty (PDF)',

    'about.awards.title': 'Giải thưởng & ghi nhận',
    'about.awards.subtitle': 'Dấu mốc ghi nhận năng lực AIoT của Udata',
    'about.awards.p1': 'Năm 2025, Uboard của Udata được vinh danh tại Giải thưởng Sao Khuê 2025 ở hạng mục Sản phẩm, giải pháp, phần mềm, dịch vụ mới. Đây là dấu mốc ghi nhận nỗ lực của Udata trong việc phát triển nền tảng AIoT giúp doanh nghiệp thu thập, giám sát, phân tích và tối ưu dữ liệu vận hành.',
    'about.awards.p2': 'Sự ghi nhận này tiếp thêm động lực để Udata tiếp tục mở rộng hệ sinh thái giải pháp, từ giám sát nhà máy, hợp nhất dữ liệu vận hành đến quản trị carbon và phát triển bền vững.',
    'about.awards.p3': '',
    'about.cta.title': 'Nói bằng dữ liệu. Đồng hành bằng kết quả.',
    'about.cta.subtitle': 'Cùng Udata xây dựng nền tảng vận hành thông minh cho doanh nghiệp của bạn',
    'about.cta.btn1': 'Khám phá giải pháp',
    'about.cta.btn2': 'Đặt lịch demo',

    // Free Trial Page
    'trial.title': 'Trải nghiệm nền tảng Udata trong 30 phút demo trực tiếp.',
    'trial.subtitle': 'Luôn hoạt động. Luôn chính xác. <br/> Udata - Đồng hành cùng doanh nghiệp trong kỷ nguyên công nghệ và bền vững.',
    'trial.list_title': 'Trong buổi demo 30 phút, chúng tôi sẽ cùng bạn khám phá:',
    'trial.item1.title': 'Tối ưu chi phí và hiệu suất',
    'trial.item1.desc': 'Xem trực tiếp cách hệ thống Udata giúp tiết kiệm điện năng, giảm chi phí vận hành và nâng cao hiệu suất thiết bị.',
    'trial.item2.title': 'Trải nghiệm demo tương tác',
    'trial.item2.desc': 'Dùng thử dashboard thực tế - theo dõi dữ liệu năng lượng, cảnh báo và báo cáo tự động.',
    'trial.item3.title': 'Tư vấn 1:1 cùng chuyên gia',
    'trial.item3.desc': 'Trao đổi về nhu cầu cụ thể của doanh nghiệp bạn, đề xuất giải pháp phù hợp cho từng mô hình vận hành.',
    'trial.item4.title': 'Tài liệu hướng dẫn & bản dùng thử miễn phí 30 ngày',
    'trial.item4.desc': 'Nhận hướng dẫn triển khai chi tiết và quyền truy cập nền tảng Udata trong 30 ngày hoàn toàn miễn phí.',
    'trial.form.title': 'Đăng ký tư vấn và dùng thử miễn phí 30 ngày cùng Udata',
    'trial.form.name': 'Họ và tên',
    'trial.form.name_placeholder': 'Nhập họ và tên',
    'trial.form.company': 'Tên công ty',
    'trial.form.company_placeholder': 'Nhập tên công ty',
    'trial.form.phone': 'Số điện thoại',
    'trial.form.phone_placeholder': 'Nhập số điện thoại',
    'trial.form.email': 'Email',
    'trial.form.email_placeholder': 'Nhập email',
    'trial.form.industry': 'Ngành nghề',
    'trial.form.industry_placeholder': 'Chọn ngành nghề',
    'trial.form.request': 'Nội dung yêu cầu thông tin',
    'trial.form.request_placeholder': 'Hãy mô tả chi tiết yêu cầu của bạn...',
    'trial.form.subscribe': 'Có, tôi muốn Udata chia sẻ cho tôi các tin tức mới nhất về dịch vụ Udata và các chương trình khuyến mãi có liên quan qua email hoặc điện thoại.',
    'trial.form.submit': 'Gửi',
    'trial.form.success': 'Gửi thông tin thành công! Chúng tôi sẽ liên hệ với bạn trong thời gian sớm nhất.',
    'trial.form.error': 'Có lỗi xảy ra. Vui lòng thử lại.',

    // Stub Pages
    'solutions.badge': 'Enterprise Solutions',
    'solutions.title': 'Giải pháp toàn diện cho <br/><span class="text-electric-cyan">chuyển đổi số</span>',
    'solutions.desc': 'Từ giám sát phần cứng đến vận hành AI, Udata cung cấp hệ sinh thái hoàn chỉnh giúp doanh nghiệp tối ưu hóa nguồn lực và bứt phá doanh thu.',
    'solutions.coming_soon': 'Trang chi tiết Giải pháp đang được thiết kế...',

    'usecases.badge': 'THỰC TIỄN DẪN ĐƯỜNG',
    'usecases.title': 'Cách doanh nghiệp ứng dụng Udata <br className="hidden md:block" />vào <span class="text-[#22D3EE] drop-shadow-[0_0_15px_rgba(34,211,238,0.3)]">vận hành thông minh</span>',
    'usecases.desc': 'Danh sách các tình huống ứng dụng thực tế từ nhiều doanh nghiệp ở đa dạng ngành nghề. Mỗi tình huống phản ánh một bài toán dữ liệu cụ thể, cách Udata kết nối, xử lý và tạo ra giá trị vận hành rõ rệt.',
    'usecases.hero.btn1': 'Khám phá tình huống ứng dụng',
    'usecases.hero.btn2': 'Liên hệ tư vấn giải pháp',
    'usecases.hero.info': 'Dữ liệu, tình huống và kết quả ở đây đều là ẩn danh hoặc tổng hợp bám sát thực tế triển khai, giúp doanh nghiệp học nhanh từ kinh nghiệm thực tế và ứng dụng hiệu quả.',
    
    'usecases.steps.title': 'Mỗi tình huống bắt đầu từ một bài toán dữ liệu cụ thể',
    'usecases.steps.desc': 'Udata giúp doanh nghiệp kết nối dữ liệu phân tán, làm sạch và chuẩn hóa dữ liệu, sau đó khai thác để giải quyết các bài toán vận hành thực tế.',
    'usecases.steps.1.title': '1. Kết nối và thu thập',
    'usecases.steps.1.desc': 'Kết nối mọi nguồn dữ liệu (vận hành, thiết bị, cảm biến, hệ thống nội bộ, bên thứ ba...) theo thời gian thực hoặc theo lịch trình.',
    'usecases.steps.2.title': '2. Chuẩn hóa và làm sạch',
    'usecases.steps.2.desc': 'Làm sạch, chuẩn hóa, loại bỏ trùng lặp và chuẩn hóa dữ liệu để đảm bảo chất lượng và khả năng sẵn sàng cho phân tích chuyên sâu.',
    'usecases.steps.3.title': '3. Lập mô hình & phân tích',
    'usecases.steps.3.desc': 'Ứng dụng AI, phân tích và mô hình hóa dữ liệu để phát hiện mẫu, dự báo và tạo ra thông tin giá trị.',
    'usecases.steps.4.title': '4. Chỉ số & theo dõi',
    'usecases.steps.4.desc': 'Biến dữ liệu thành chỉ số và báo cáo trực quan, hỗ trợ ra quyết định nhanh và hành động kịp thời.',

    'usecases.grid.title': 'Tình huống ứng dụng nổi bật',
    'usecases.grid.desc': 'Các tình huống được chọn lọc từ nhiều ngành nghề. Bạn có thể lọc theo sản phẩm Udata để xem những ví dụ phù hợp nhất với nhu cầu của mình.',
    'usecases.grid.filter.all': 'Tất cả',

    'usecases.metrics.title': 'Các chỉ số doanh nghiệp có thể theo dõi',
    'usecases.metrics.desc': 'Tập trung vào các chỉ số vận hành & kinh doanh cốt lõi, có thể đo lường và cải thiện thông qua dữ liệu.',
    'usecases.metrics.1.title': 'Hiệu suất vận hành',
    'usecases.metrics.1.items': '• OEE, năng suất, sản lượng|• Tỷ lệ lỗi, phế phẩm|• Thời gian dừng máy',
    'usecases.metrics.2.title': 'Chuỗi & tồn kho',
    'usecases.metrics.2.items': '• Tỷ lệ tồn kho, vòng quay|• Tỷ lệ giao hàng đúng hạn|• Thời gian chu kỳ đơn hàng',
    'usecases.metrics.3.title': 'Năng lượng & tài nguyên',
    'usecases.metrics.3.items': '• Tiêu thụ điện, nước, nhiệt|• Hiệu suất sử dụng tài nguyên|• Phát hiện lãng phí',
    'usecases.metrics.4.title': 'Carbon & môi trường',
    'usecases.metrics.4.items': '• Phát thải CO₂e|• Tỷ lệ tuân thủ môi trường|• Chỉ số ESG tổng hợp',
    'usecases.metrics.5.title': 'Tài chính & kinh doanh',
    'usecases.metrics.5.items': '• Doanh thu, lợi nhuận|• Chi phí vận hành|• Tỷ suất sinh lời',

    'usecases.cta.title': 'Bạn đang muốn giải quyết bài toán vận hành nào?',
    'usecases.cta.desc': 'Hãy để Udata đồng hành cùng bạn xây dựng hệ thống dữ liệu và phân tích phù hợp với thực tế doanh nghiệp.',
    'usecases.cta.btn1': 'Yêu cầu tư vấn',
    'usecases.cta.btn2': 'Tài liệu giải pháp',

    'sustainability.badge': 'Tầm nhìn 2050',
    'sustainability.title': 'Phát triển <span class="text-sustain-teal">Bền vững</span> <br/>với Green AI',
    'sustainability.desc': 'Udata cam kết đồng hành cùng doanh nghiệp đo lường phát thải, tối ưu hóa năng lượng và hướng tới mục tiêu Net Zero toàn cầu.',
    'sustainability.coming_soon': 'Báo cáo Phát triển bền vững đang được chuẩn bị...',

    'blog.badge': 'Tin tức & Bài viết',
    'blog.title': 'Khám phá tri thức cùng <br/><span class="text-electric-cyan">Udata Blog</span>',
    'blog.desc': 'Cập nhật những xu hướng công nghệ mới nhất về AI, IoT, chuyển đổi số và phát triển bền vững từ các chuyên gia của chúng tôi.',
    'blog.coming_soon': 'Trang bài viết đang được cập nhật nội dung...',

    // Build to Order Page
    'bto.hero.badge': 'DỊCH VỤ PHÁT TRIỂN PHẦN MỀM THEO YÊU CẦU',
    'bto.hero.title': 'Phát Triển Theo Yêu Cầu',
    'bto.hero.subtitle': 'Giải phóng gánh nặng kỹ thuật. Cung cấp giải pháp phần mềm tùy chỉnh phù hợp với nhu cầu kinh doanh độc đáo của bạn.',
    'bto.hero.btn1': 'Đặt lịch tư vấn trực tuyến',
    'bto.hero.btn2': 'Xem Hồ sơ năng lực',
    
    'bto.benefits.badge': 'LỢI ÍCH KHI OUTSOURCE PHẦN MỀM',
    'bto.benefits.title': 'Tại Sao Nên Xây Dựng Phần Mềm Cùng Udata?',
    'bto.benefits.desc': 'Mỗi dự án đều có đặc thù riêng và đó là lý do chúng tôi ở đây. Đội ngũ của Udata luôn sẵn sàng đón nhận các bài toán phức tạp.',
    'bto.benefits.b1.title': 'Khởi động trong 2-4 Tuần',
    'bto.benefits.b1.desc': 'Chúng tôi nhanh chóng tập hợp những nhân sự tài năng phù hợp với yêu cầu dự án của bạn.',
    'bto.benefits.b2.title': 'Giao hàng trọn gói (End-to-End)',
    'bto.benefits.b2.desc': 'Không chỉ lập trình, chúng tôi đảm nhận cả thiết kế UI/UX, kiểm thử và triển khai.',
    'bto.benefits.b3.title': 'Giao tiếp rõ ràng',
    'bto.benefits.b3.desc': 'Trao đổi trực tiếp với kỹ sư đảm bảo tầm nhìn của bạn được hiện thực hóa chính xác.',
    'bto.benefits.b4.title': 'Chuyên gia giàu kinh nghiệm',
    'bto.benefits.b4.desc': 'Các quản lý kỹ thuật cấp cao luôn giám sát kiến trúc hệ thống và chất lượng mã nguồn.',
    
    'bto.process.badge': 'QUY TRÌNH',
    'bto.process.title': 'Quy Trình Phát Triển Phần Mềm',
    'bto.process.desc': 'Chúng tôi cung cấp các giải pháp đáp ứng chính xác phạm vi, tiến độ và ngân sách với tỷ lệ hoàn thành đúng hạn 95%.',
    'bto.process.s1.title': 'Khảo sát & Phân tích',
    'bto.process.s1.desc': 'Chúng tôi đi sâu vào nghiệp vụ của bạn để thống nhất mục tiêu, làm rõ phạm vi và dự báo rủi ro.',
    'bto.process.s2.title': 'Thiết kế UI/UX',
    'bto.process.s2.desc': 'Chuyển đổi ý tưởng thành giao diện mượt mà, thân thiện với người dùng và kiểm chứng cùng các bên liên quan.',
    'bto.process.s3.title': 'Phát triển Phần mềm',
    'bto.process.s3.desc': 'Triển khai qua các sprint ngắn hạn, theo dõi tiến độ hàng ngày với tính minh bạch tuyệt đối.',
    'bto.process.s4.title': 'Kiểm thử & Đảm bảo Chất lượng',
    'bto.process.s4.desc': 'Các tính năng đều trải qua quá trình kiểm thử tự động và hồi quy nghiêm ngặt để đảm bảo sản phẩm ổn định.',
    
    'bto.why.badge': 'TẠI SAO CHỌN UDATA',
    'bto.why.title': 'Lý Do Lựa Chọn Udata?',
    'bto.why.w1.title': 'Mở rộng linh hoạt & Bảo mật',
    'bto.why.w1.desc': 'Kiến trúc được thiết kế để mở rộng cùng cơ sở người dùng và bảo vệ dữ liệu nhạy cảm của bạn.',
    'bto.why.w2.title': 'Cộng tác theo thời gian thực',
    'bto.why.w2.desc': 'Các buổi standup hàng ngày, sprint review và demo trực tiếp giúp bạn luôn nắm bắt tiến độ.',
    'bto.why.w3.title': 'Chất lượng hàng đầu',
    'bto.why.w3.desc': 'Chúng tôi ưu tiên mã nguồn sạch, độ phủ test cao và hệ thống dễ bảo trì.',
    
    'bto.faq.badge': 'HỎI ĐÁP',
    'bto.faq.title': 'Câu Hỏi Thường Gặp',
    'bto.faq.desc': 'Tất cả những gì bạn cần biết về dịch vụ Phát triển phần mềm theo yêu cầu của chúng tôi.',
    'bto.faq.q1.q': 'Mất bao lâu để hoàn thành một phần mềm theo yêu cầu?',
    'bto.faq.q1.a': 'Tùy thuộc vào độ phức tạp, một phiên bản MVP thường mất 2-3 tháng, trong khi các giải pháp doanh nghiệp toàn diện mất từ 6 tháng trở lên.',
    'bto.faq.q2.q': 'Có bất kỳ chi phí ẩn nào không?',
    'bto.faq.q2.a': 'Không. Chúng tôi cung cấp ước tính chi phí minh bạch và mọi thay đổi về phạm vi đều được bạn phê duyệt trước khi phát sinh chi phí.',
    'bto.faq.q3.q': 'Làm thế nào để bạn chọn được stack công nghệ phù hợp?',
    'bto.faq.q3.a': 'Chúng tôi đánh giá nhu cầu hiệu suất, mục tiêu mở rộng, chuyên môn của đội ngũ và ngân sách để chọn ra giải pháp công nghệ tối ưu nhất.',

    // Offshore Dev Teams Page
    'odc.hero.badge': 'TRUNG TÂM PHÁT TRIỂN OFFSHORE (ODC)',
    'odc.hero.title': 'Trung Tâm Offshore',
    'odc.hero.subtitle': 'Giải pháp phát triển phần mềm tối ưu. Xây dựng đội ngũ chuyên trách linh hoạt, bảo mật tuyệt đối với đội ngũ chuyên gia.',
    'odc.hero.btn1': 'Đặt lịch tư vấn trực tuyến',
    'odc.hero.btn2': 'Xem Hồ sơ năng lực',
    
    'odc.benefits.badge': 'LỢI ÍCH KHI SỬ DỤNG DỊCH VỤ OFFSHORE',
    'odc.benefits.title': 'Tại Sao Nên Xây Dựng Đội Ngũ Cùng Udata?',
    'odc.benefits.desc': 'Tận dụng hạ tầng thiết lập sẵn, nguồn nhân lực chất lượng cao và quy trình chuẩn hóa để mở rộng năng lực kỹ thuật một cách nhanh chóng.',
    'odc.benefits.b1.title': 'Chuyển giao Kiến thức',
    'odc.benefits.b1.desc': 'Quy trình onboarding mượt mà và chia sẻ kiến thức liên tục giúp ODC hoạt động như một bộ phận mở rộng thực sự.',
    'odc.benefits.b2.title': 'Nhân sự Ổn định',
    'odc.benefits.b2.desc': 'Mở rộng hoặc thu hẹp đội ngũ theo lộ trình mà không lo gánh nặng tuyển dụng và rủi ro nhân sự nghỉ việc.',
    'odc.benefits.b3.title': 'Bảo mật & Bảo vệ IP',
    'odc.benefits.b3.desc': 'Chính sách bảo mật nghiêm ngặt và thỏa thuận NDA đảm bảo tài sản trí tuệ và dữ liệu của bạn hoàn toàn an toàn.',
    'odc.benefits.b4.title': 'Cam kết Chất lượng',
    'odc.benefits.b4.desc': 'Chất lượng được tích hợp vào mọi giai đoạn, từ tuyển dụng đến lúc bàn giao mã nguồn và bảo trì.',
    
    'odc.tech.badge': 'CÔNG NGHỆ CỐT LÕI',
    'odc.tech.title': 'Năng Lực Công Nghệ',
    'odc.tech.desc': 'Chúng tôi lựa chọn công nghệ phù hợp với mục tiêu, quy mô và ngân sách của bạn — đánh giá hiệu năng, bảo mật và chi phí hạ tầng.',
    
    'odc.why.badge': 'TẠI SAO CHỌN MÔ HÌNH ODC CỦA UDATA',
    'odc.why.title': 'Lý Do Đồng Hành Cùng Chúng Tôi',
    'odc.why.w1.title': 'Xây Dựng "MỘT ĐỘI NGŨ" Cùng Khách Hàng',
    'odc.why.w1.desc': 'Chúng tôi hòa nhập sâu vào văn hóa của bạn, làm việc như một phần mở rộng liền mạch của đội ngũ nội bộ với cùng một mục tiêu.',
    'odc.why.w2.title': 'Sự Đồng Hành Dài Hạn',
    'odc.why.w2.desc': 'Chúng tôi không chỉ viết code; chúng tôi sát cánh cùng bạn trong quá trình chuyển đổi số và phát triển chiến lược dài hạn.',
    'odc.why.w3.title': 'Tối Ưu Chi Phí',
    'odc.why.w3.desc': 'Tối ưu ngân sách phát triển phần mềm nhờ các mô hình giá minh bạch và nguồn nhân lực offshore hiệu quả.',
    
    'odc.faq.badge': 'HỎI ĐÁP',
    'odc.faq.title': 'Câu Hỏi Thường Gặp',
    'odc.faq.desc': 'Tất cả những gì bạn cần biết về dịch vụ Trung tâm Offshore (ODC) của chúng tôi.',
    'odc.faq.q1.q': 'Quy mô đội ngũ phát triển của bạn là bao nhiêu?',
    'odc.faq.q1.a': 'Chúng tôi có mạng lưới hơn 500 kỹ sư, cho phép xây dựng đội ngũ từ 5 đến 50+ thành viên theo nhu cầu của bạn.',
    'odc.faq.q2.q': 'Làm thế nào để đảm bảo giao tiếp hiệu quả?',
    'odc.faq.q2.a': 'Chúng tôi đồng bộ múi giờ, thiết lập các buổi standup hàng ngày và sử dụng các công cụ quản lý dự án để đảm bảo giao tiếp minh bạch.',
    'odc.faq.q3.q': 'Bạn có biện pháp bảo mật nào để bảo vệ dữ liệu?',
    'odc.faq.q3.a': 'Chúng tôi áp dụng thỏa thuận bảo mật NDA nghiêm ngặt, giao thức mạng an toàn, quy trình đạt chuẩn ISO và các chính sách bảo vệ dữ liệu toàn diện.',
  }
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');

  const toggleLang = () => {
    setLang(lang === 'VI' ? 'EN' : 'VI');
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);


