const routeMaps = {
  vi: {
    "/en/free-trial": "/dung-thu",
    "/en/about-company": "/ve-cong-ty",
    "/en/career": "/tuyen-dung",
    "/en/product/saas-platform": "/san-pham/nen-tang-saas",
    "/en/product/data-integration": "/san-pham/tich-hop-du-lieu",
    "/en/solution/investors": "/giai-phap/nha-dau-tu",
    "/en/solution/senior-managers": "/giai-phap/nha-quan-ly-cap-cao",
    "/en/solution/operators": "/giai-phap/nha-quan-ly-van-hanh",
    "/en/solution/solar-rooftop": "/giai-phap/solar-rooftop",
    "/en/solution/factory": "/giai-phap/nha-may",
    "/en/solution/fisheries": "/giai-phap/thuy-san",
    "/en/notification": "/thong-bao",
    "/en/blog": "/blog",
  },
  en: {
    "/dung-thu": "/en/free-trial",
    "/ve-cong-ty": "/en/about-company",
    "/tuyen-dung": "/en/career",
    "/san-pham/nen-tang-saas": "/en/product/saas-platform",
    "/san-pham/tich-hop-du-lieu": "/en/product/data-integration",
    "/giai-phap/nha-dau-tu": "/en/solution/investors",
    "/giai-phap/nha-quan-ly-cap-cao": "/en/solution/senior-managers",
    "/giai-phap/nha-quan-ly-van-hanh": "/en/solution/operators",
    "/giai-phap/solar-rooftop": "/en/solution/solar-rooftop",
    "/giai-phap/nha-may": "/en/solution/factory",
    "/giai-phap/thuy-san": "/en/solution/fisheries",
    "/thong-bao": "/en/notification",
    "/blog": "/en/blog",
  },
  jp: {
    "/dung-thu": "/jp/free-trial",
    "/ve-cong-ty": "/jp/about-company",
    "/tuyen-dung": "/jp/career",
    "/san-pham/nen-tang-saas": "/jp/product/saas-platform",
    "/san-pham/tich-hop-du-lieu": "/jp/product/data-integration",
    "/giai-phap/nha-dau-tu": "/jp/solution/investors",
    "/giai-phap/nha-quan-ly-cap-cao": "/jp/solution/senior-managers",
    "/giai-phap/nha-quan-ly-van-hanh": "/jp/solution/operators",
    "/giai-phap/solar-rooftop": "/jp/solution/solar-rooftop",
    "/giai-phap/nha-may": "/jp/solution/factory",
    "/giai-phap/thuy-san": "/jp/solution/fisheries",
    "/thong-bao": "/jp/notification",
    "/blog": "/jp/blog",
  },
  th: {
    "/dung-thu": "/th/free-trial",
    "/ve-cong-ty": "/th/about-company",
    "/tuyen-dung": "/th/career",
    "/san-pham/nen-tang-saas": "/th/product/saas-platform",
    "/san-pham/tich-hop-du-lieu": "/th/product/data-integration",
    "/giai-phap/nha-dau-tu": "/th/solution/investors",
    "/giai-phap/nha-quan-ly-cap-cao": "/th/solution/senior-managers",
    "/giai-phap/nha-quan-ly-van-hanh": "/th/solution/operators",
    "/giai-phap/solar-rooftop": "/th/solution/solar-rooftop",
    "/giai-phap/nha-may": "/th/solution/factory",
    "/giai-phap/thuy-san": "/th/solution/fisheries",
    "/thong-bao": "/th/notification",
    "/blog": "/th/blog",
  },
};

module.exports = { routeMaps };
